import type { Hotel } from '../types';

const checked = '2026-08-07';

function bookingSearch(hotelName: string): string {
  const query = encodeURIComponent(`${hotelName}, Nashville, Tennessee`);
  return `https://www.booking.com/searchresults.html?ss=${query}`;
}

const sharedSourceNote =
  'Real operating Nashville hotel. Core identity and location checked against current hotel/Booking.com sources on 2026-08-07. High-level amenities and parking notes should be refreshed from the future hotel provider before marking verified.';

/**
 * Real Nashville hotel inventory with Booking.com search links as a temporary
 * booking layer. No Booking.com property IDs, live rates, availability,
 * ratings, or reviews are fabricated here.
 */
export const hotels: Hotel[] = [
  {
    kind: 'hotel',
    slug: '1-hotel-nashville',
    title: '1 Hotel Nashville',
    summary: 'A sustainability-minded luxury hotel beside Nashville Yards, close to the arena and Lower Broadway.',
    whyWeRecommend: 'A strong luxury choice for travelers who want a modern wellness-forward stay and an easy walk to the downtown core.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$$',
    bestFor: ['Luxury', 'Couples', 'Wellness', 'Walkable stays'],
    address: '710 Demonbreun St, Nashville, TN 37203',
    amenities: ['Fitness center', 'Spa and wellness', 'Rooftop', 'On-site dining'],
    parkingNote: 'Downtown hotel parking is paid; confirm current valet/self-parking options before arrival.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for Bridgestone Arena, Music City Center, Broadway and Nashville Yards.',
    nearbyAttractions: ['Bridgestone Arena', 'Lower Broadway', 'Music City Center', 'Nashville Yards'],
    bookingUrl: bookingSearch('1 Hotel Nashville'),
    mapQuery: '1 Hotel Nashville, Nashville, TN',
    relatedSlugs: ['the-joseph-nashville', 'jw-marriott-nashville', 'grand-hyatt-nashville'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'the-joseph-nashville',
    title: 'The Joseph, a Luxury Collection Hotel, Nashville',
    summary: 'A polished luxury hotel in SoBro with a rooftop pool, spa and strong access to the Music City Center.',
    whyWeRecommend: 'A refined downtown option when the hotel itself matters as much as the location.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$$',
    bestFor: ['Luxury', 'Couples', 'Special occasions', 'Downtown'],
    address: '401 Korean Veterans Blvd, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Spa', 'Fitness center', 'On-site dining'],
    parkingNote: 'Valet/paid downtown parking; confirm the current nightly rate with the hotel.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Very strong for SoBro, the convention center, Bridgestone Arena and Lower Broadway.',
    nearbyAttractions: ['Music City Center', 'Country Music Hall of Fame', 'Bridgestone Arena', 'Lower Broadway'],
    bookingUrl: bookingSearch('The Joseph Nashville'),
    mapQuery: 'The Joseph Nashville, Nashville, TN',
    relatedSlugs: ['four-seasons-hotel-nashville', '1-hotel-nashville', 'omni-nashville-hotel'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'four-seasons-hotel-nashville',
    title: 'Four Seasons Hotel Nashville',
    summary: 'A river-facing luxury hotel in SoBro, one block from Broadway with a rooftop pool and spa.',
    whyWeRecommend: 'The premium choice for travelers who want five-star service and still want to walk to Broadway and the riverfront.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$$',
    bestFor: ['Luxury', 'Couples', 'River views', 'Special occasions'],
    address: '100 Demonbreun St, Nashville, TN 37201',
    amenities: ['Rooftop pool', 'Spa', 'Fitness center', 'On-site dining'],
    parkingNote: 'Valet/paid downtown parking; confirm current rates with the property.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for Broadway, Ascend Amphitheater, the riverfront and Bridgestone Arena.',
    nearbyAttractions: ['Cumberland Riverfront', 'Ascend Amphitheater', 'Lower Broadway', 'Bridgestone Arena'],
    bookingUrl: bookingSearch('Four Seasons Hotel Nashville'),
    mapQuery: 'Four Seasons Hotel Nashville, Nashville, TN',
    relatedSlugs: ['the-joseph-nashville', 'omni-nashville-hotel', '1-hotel-nashville'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'omni-nashville-hotel',
    title: 'Omni Nashville Hotel',
    summary: 'A large full-service downtown hotel integrated with the Country Music Hall of Fame and across from Music City Center.',
    whyWeRecommend: 'Hard to beat for conventions, families and first-time visitors who want major attractions at the front door.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$',
    bestFor: ['First-time visitors', 'Conventions', 'Families', 'Downtown'],
    address: '250 Rep. John Lewis Way S, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Spa', 'Fitness center', 'Multiple dining options'],
    parkingNote: 'Paid downtown parking and valet are available; confirm current pricing before arrival.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for the Country Music Hall of Fame, Music City Center, Bridgestone Arena and Broadway.',
    nearbyAttractions: ['Country Music Hall of Fame', 'Music City Center', 'Bridgestone Arena', 'Lower Broadway'],
    bookingUrl: bookingSearch('Omni Nashville Hotel'),
    mapQuery: 'Omni Nashville Hotel, Nashville, TN',
    relatedSlugs: ['the-joseph-nashville', 'four-seasons-hotel-nashville', 'jw-marriott-nashville'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'jw-marriott-nashville',
    title: 'JW Marriott Nashville',
    summary: 'A high-rise luxury hotel just south of Broadway with skyline views and a rooftop pool.',
    whyWeRecommend: 'A reliable luxury downtown choice for travelers who want Broadway nearby without sleeping directly on it.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$$',
    bestFor: ['Luxury', 'Business travel', 'Couples', 'Arena events'],
    address: '201 8th Ave S, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Spa', 'Fitness center', 'On-site dining'],
    parkingNote: 'Paid valet/garage parking; confirm current nightly pricing.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Strong downtown position near Bridgestone Arena, the convention center and Lower Broadway.',
    nearbyAttractions: ['Bridgestone Arena', 'Music City Center', 'Lower Broadway', 'Nashville Yards'],
    bookingUrl: bookingSearch('JW Marriott Nashville'),
    mapQuery: 'JW Marriott Nashville, Nashville, TN',
    relatedSlugs: ['1-hotel-nashville', 'grand-hyatt-nashville', 'the-joseph-nashville'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'grand-hyatt-nashville',
    title: 'Grand Hyatt Nashville',
    summary: 'A large upscale hotel at Nashville Yards on Broadway, between downtown and the West End/Midtown corridor.',
    whyWeRecommend: 'Good for travelers who want a full-service hotel, rooftop pool and access to both Broadway and Nashville Yards.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$$',
    bestFor: ['Business travel', 'Luxury', 'Groups', 'Nashville Yards'],
    address: '1000 Broadway, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Spa', 'Fitness center', 'On-site dining'],
    parkingNote: 'Paid downtown parking; confirm current valet and self-parking rates.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Walkable to Nashville Yards, the Gulch and Lower Broadway.',
    nearbyAttractions: ['Nashville Yards', 'The Gulch', 'Lower Broadway', 'Frist Art Museum'],
    bookingUrl: bookingSearch('Grand Hyatt Nashville'),
    mapQuery: 'Grand Hyatt Nashville, Nashville, TN',
    relatedSlugs: ['1-hotel-nashville', 'jw-marriott-nashville', 'conrad-nashville'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'thompson-nashville',
    title: 'Thompson Nashville, by Hyatt',
    summary: 'A design-forward hotel in the heart of the Gulch with a rooftop bar and street-level dining.',
    whyWeRecommend: 'One of the most natural fits for a stylish Gulch weekend without staying directly on Broadway.',
    neighborhood: 'the-gulch',
    priceCategory: '$$$$',
    bestFor: ['Couples', 'The Gulch', 'Food and drink', 'Design'],
    address: '401 11th Ave S, Nashville, TN 37203',
    amenities: ['Rooftop bar', 'Fitness center', 'On-site dining', 'Coffee shop'],
    parkingNote: 'Valet/paid parking; nearby Gulch garages provide alternatives.',
    hasPool: false,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent inside the Gulch and roughly a 15-20 minute walk to Lower Broadway.',
    nearbyAttractions: ['Station Inn', 'The Gulch', 'Nashville Yards', 'Lower Broadway'],
    bookingUrl: bookingSearch('Thompson Nashville'),
    mapQuery: 'Thompson Nashville, Nashville, TN',
    relatedSlugs: ['w-nashville', '1-hotel-nashville', 'grand-hyatt-nashville'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'w-nashville',
    title: 'W Nashville',
    summary: 'A large lifestyle hotel in the Gulch with a rooftop pool and an active social scene.',
    whyWeRecommend: 'The stronger Gulch fit for groups who want the hotel to be part of the weekend rather than simply a place to sleep.',
    neighborhood: 'the-gulch',
    priceCategory: '$$$$',
    bestFor: ['Groups', 'The Gulch', 'Pool weekends', 'Nightlife'],
    address: '300 12th Ave S, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Fitness center', 'Multiple dining options', 'Bars'],
    parkingNote: 'Valet/paid parking; self-parking garages are available around the Gulch.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for the Gulch, with downtown and Nashville Yards close enough to walk for most visitors.',
    nearbyAttractions: ['The Gulch', 'Station Inn', 'Nashville Yards', 'Lower Broadway'],
    bookingUrl: bookingSearch('W Nashville'),
    mapQuery: 'W Nashville, Nashville, TN',
    relatedSlugs: ['thompson-nashville', '1-hotel-nashville', 'grand-hyatt-nashville'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'conrad-nashville',
    title: 'Conrad Nashville',
    summary: 'A modern luxury hotel on West End near Music Row with a rooftop pool terrace.',
    whyWeRecommend: 'A strong upscale choice for travelers who want luxury and a pool without committing to the downtown party zone.',
    neighborhood: 'midtown',
    priceCategory: '$$$$',
    bestFor: ['Luxury', 'Couples', 'Music Row', 'Pool'],
    address: '1620 West End Ave, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Fitness center', 'On-site dining', 'Concierge'],
    parkingNote: 'Paid self-parking and valet are available; confirm current rates.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Good for Music Row and Midtown; Broadway is a short ride or a longer walk.',
    nearbyAttractions: ['Music Row', 'Midtown', 'Vanderbilt University', 'Nashville Yards'],
    bookingUrl: bookingSearch('Conrad Nashville'),
    mapQuery: 'Conrad Nashville, Nashville, TN',
    relatedSlugs: ['graduate-nashville', 'hutton-hotel', 'holiday-inn-nashville-vanderbilt'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'graduate-nashville',
    title: 'Graduate by Hilton Nashville',
    summary: 'A playful themed hotel near Vanderbilt and Music Row with a rooftop restaurant and pool scene.',
    whyWeRecommend: 'A memorable alternative to the polished downtown towers for younger groups and repeat visitors.',
    neighborhood: 'midtown',
    priceCategory: '$$$',
    bestFor: ['Groups', 'Design', 'Vanderbilt', 'Rooftop'],
    address: '101 20th Ave N, Nashville, TN 37203',
    amenities: ['Rooftop', 'Pool', 'Fitness center', 'On-site dining'],
    parkingNote: 'Paid hotel parking; confirm current self-park/valet options.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for Vanderbilt and nearby Midtown/Music Row; downtown is a short ride.',
    nearbyAttractions: ['Vanderbilt University', 'Music Row', 'Midtown', 'Centennial Park'],
    bookingUrl: bookingSearch('Graduate by Hilton Nashville'),
    mapQuery: 'Graduate Nashville, Nashville, TN',
    relatedSlugs: ['conrad-nashville', 'hutton-hotel', 'holiday-inn-nashville-vanderbilt'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'hutton-hotel',
    title: 'Hutton Hotel',
    summary: 'A music-focused boutique hotel on West End with an intimate live-music venue and songwriter studios.',
    whyWeRecommend: 'A good repeat-visitor option when Music Row and Nashville’s creative side matter more than walking straight onto Broadway.',
    neighborhood: 'midtown',
    priceCategory: '$$$',
    bestFor: ['Music-focused trips', 'Couples', 'Business travel', 'Midtown'],
    address: '1808 West End Ave, Nashville, TN 37203',
    amenities: ['Fitness center', 'Live music venue', 'Writers studios', 'On-site food and drink'],
    parkingNote: 'Paid hotel parking/valet; confirm current rates.',
    hasPool: false,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Good for Midtown, Music Row and Vanderbilt; downtown is usually easier by rideshare.',
    nearbyAttractions: ['Music Row', 'Vanderbilt University', 'Midtown', 'Centennial Park'],
    bookingUrl: bookingSearch('Hutton Hotel Nashville'),
    mapQuery: 'Hutton Hotel Nashville, Nashville, TN',
    relatedSlugs: ['conrad-nashville', 'graduate-nashville', 'holiday-inn-nashville-vanderbilt'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'holiday-inn-nashville-vanderbilt',
    title: 'Holiday Inn Nashville-Vanderbilt (Dwtn) by IHG',
    summary: 'A practical West End hotel directly across from Centennial Park with a seasonal pool and Vanderbilt access.',
    whyWeRecommend: 'A sensible value option for families and Vanderbilt trips.',
    neighborhood: 'midtown',
    priceCategory: '$$',
    bestFor: ['Value', 'Families', 'Vanderbilt', 'Centennial Park'],
    address: '2613 West End Ave, Nashville, TN 37203',
    amenities: ['Seasonal pool', 'Fitness center', 'On-site dining', 'Area shuttle'],
    parkingNote: 'On-site parking is available; confirm the current nightly charge.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for Centennial Park and Vanderbilt; downtown is best reached by a short ride.',
    nearbyAttractions: ['Centennial Park', 'The Parthenon', 'Vanderbilt University', 'West End'],
    bookingUrl: bookingSearch('Holiday Inn Nashville Vanderbilt'),
    mapQuery: 'Holiday Inn Nashville Vanderbilt, Nashville, TN',
    relatedSlugs: ['graduate-nashville', 'hutton-hotel', 'conrad-nashville'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'germantown-inn',
    title: 'Germantown Inn',
    summary: 'A small boutique inn in historic Germantown, apart from the larger downtown hotel towers.',
    whyWeRecommend: 'A good fit for travelers who care more about neighborhood restaurants and quiet residential character than big-hotel amenities.',
    neighborhood: 'germantown',
    priceCategory: '$$$',
    bestFor: ['Couples', 'Boutique stays', 'Food-focused trips', 'Quiet stays'],
    address: '1218 6th Ave N, Nashville, TN 37208',
    amenities: ['Breakfast', 'Courtyard and common areas', 'Boutique rooms', 'Neighborhood setting'],
    parkingNote: 'Confirm current on-site/street parking arrangements with the inn before arrival.',
    hasPool: false,
    hasFitness: false,
    familyFriendly: true,
    walkabilityNote: 'Excellent for Germantown restaurants, Bicentennial Capitol Mall and the Farmers Market.',
    nearbyAttractions: ['Nashville Farmers Market', 'Bicentennial Capitol Mall', 'First Horizon Park', 'Tennessee State Capitol'],
    bookingUrl: bookingSearch('Germantown Inn Nashville'),
    mapQuery: 'Germantown Inn Nashville, Nashville, TN',
    relatedSlugs: ['the-joseph-nashville', 'grand-hyatt-nashville', 'omni-nashville-hotel'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'hilton-nashville-green-hills',
    title: 'Hilton Nashville Green Hills',
    summary: 'A modern full-service hotel in Green Hills with a rooftop pool and access to shopping and the Bluebird Cafe.',
    whyWeRecommend: 'A useful option for travelers who want a quieter base away from downtown nightlife.',
    neighborhood: 'green-hills',
    priceCategory: '$$$',
    bestFor: ['Shopping', 'Business travel', 'Quiet stays', 'Green Hills'],
    address: '3801 Cleghorn Ave, Nashville, TN 37215',
    amenities: ['Rooftop pool', 'Fitness center', 'On-site dining', 'Meeting space'],
    parkingNote: 'On-site parking is available; confirm current pricing.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Walkable to Green Hills shopping and nearby restaurants; downtown requires a drive or rideshare.',
    nearbyAttractions: ['The Mall at Green Hills', 'Bluebird Cafe', 'Green Hills restaurants', 'Radnor Lake'],
    bookingUrl: bookingSearch('Hilton Nashville Green Hills'),
    mapQuery: 'Hilton Nashville Green Hills, Nashville, TN',
    relatedSlugs: ['holiday-inn-nashville-vanderbilt', 'graduate-nashville', 'germantown-inn'],
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote: sharedSourceNote,
    placement: 'affiliate',
  },
];

export function getHotel(slug: string): Hotel | undefined {
  return hotels.find((hotel) => hotel.slug === slug);
}
