import type { Hotel } from '../types';
import { partners } from '../partners';

type HotelSeed = Omit<
  Hotel,
  'kind' | 'dataStatus' | 'dateChecked' | 'dateUpdated' | 'sourceNote' | 'placement' | 'bookingUrl' | 'image'
> & {
  bookingQuery?: string;
};

const checked = '2026-08-07';

function realHotel({ bookingQuery, ...hotel }: HotelSeed): Hotel {
  return {
    kind: 'hotel',
    ...hotel,
    bookingUrl: partners.hotels.build({ area: bookingQuery || hotel.title }),
    dataStatus: 'needs-recheck',
    dateChecked: checked,
    dateUpdated: checked,
    sourceNote:
      'Real operating Nashville hotel. Core identity and location checked against current hotel/Booking.com sources on 2026-08-07. High-level amenities and parking notes should be refreshed from the future hotel provider before marking verified.',
    placement: 'affiliate',
  };
}

/**
 * Initial real Nashville hotel catalog.
 *
 * Booking.com is intentionally only a deep-link/search placeholder here. We do
 * not fabricate Booking.com property IDs, rates, availability, ratings, or
 * reviews. When Demand API access is approved, the provider layer can replace
 * these search links without changing the editorial hotel model or page URLs.
 */
export const hotels: Hotel[] = [
  realHotel({
    slug: '1-hotel-nashville',
    title: '1 Hotel Nashville',
    summary: 'A sustainability-minded luxury hotel beside Nashville Yards, close to the arena and Lower Broadway without sitting directly over the nightlife.',
    whyWeRecommend: 'One of the strongest luxury choices for travelers who want a modern wellness-forward stay and an easy walk to the core downtown attractions.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$$',
    bestFor: ['Luxury', 'Couples', 'Wellness', 'Walkable stays'],
    address: '710 Demonbreun St, Nashville, TN 37203',
    amenities: ['Fitness center', 'Spa and wellness', 'Rooftop', 'On-site dining'],
    parkingNote: 'Downtown hotel parking is paid; confirm current valet/self-parking options before arrival.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for Bridgestone Arena, the Music City Center, Broadway and Nashville Yards; most downtown stops are within a 10-15 minute walk.',
    nearbyAttractions: ['Bridgestone Arena', 'Lower Broadway', 'Music City Center', 'Nashville Yards'],
    mapQuery: '1 Hotel Nashville, Nashville, TN',
    relatedSlugs: ['the-joseph-nashville', 'jw-marriott-nashville', 'grand-hyatt-nashville'],
  }),
  realHotel({
    slug: 'the-joseph-nashville',
    title: 'The Joseph, a Luxury Collection Hotel, Nashville',
    summary: 'A polished luxury hotel in SoBro with a rooftop pool, spa and a strong food-and-beverage program near the Music City Center.',
    whyWeRecommend: 'A refined downtown option when the hotel itself matters as much as the location, with quick access to Broadway but a more grown-up feel than the nightlife blocks.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$$',
    bestFor: ['Luxury', 'Couples', 'Special occasions', 'Downtown'],
    address: '401 Korean Veterans Blvd, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Spa', 'Fitness center', 'On-site dining'],
    parkingNote: 'Valet/paid downtown parking; confirm the current nightly rate with the hotel.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Very strong for SoBro, the convention center, Bridgestone Arena and Lower Broadway.',
    nearbyAttractions: ['Music City Center', 'Country Music Hall of Fame', 'Bridgestone Arena', 'Lower Broadway'],
    mapQuery: 'The Joseph Nashville, Nashville, TN',
    relatedSlugs: ['four-seasons-hotel-nashville', '1-hotel-nashville', 'omni-nashville-hotel'],
  }),
  realHotel({
    slug: 'four-seasons-hotel-nashville',
    title: 'Four Seasons Hotel Nashville',
    summary: 'A river-facing luxury hotel in SoBro, one block from Broadway with a rooftop pool, spa and full-service dining.',
    whyWeRecommend: 'The premium choice for travelers who want true five-star service and still want to walk to the arena, Broadway and the riverfront.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$$',
    bestFor: ['Luxury', 'Couples', 'River views', 'Special occasions'],
    address: '100 Demonbreun St, Nashville, TN 37201',
    amenities: ['Rooftop pool', 'Spa', 'Fitness center', 'On-site dining'],
    parkingNote: 'Valet/paid downtown parking; confirm current rates with the property.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent downtown location with Broadway, Ascend Amphitheater, the riverfront and Bridgestone Arena nearby.',
    nearbyAttractions: ['Cumberland Riverfront', 'Ascend Amphitheater', 'Lower Broadway', 'Bridgestone Arena'],
    mapQuery: 'Four Seasons Hotel Nashville, Nashville, TN',
    relatedSlugs: ['the-joseph-nashville', 'omni-nashville-hotel', 'the-hermitage-hotel'],
  }),
  realHotel({
    slug: 'omni-nashville-hotel',
    title: 'Omni Nashville Hotel',
    summary: 'A large full-service downtown hotel integrated with the Country Music Hall of Fame and directly across from the Music City Center.',
    whyWeRecommend: 'Hard to beat for conventions, families and first-time visitors who want major attractions at the front door and plenty of hotel amenities.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$',
    bestFor: ['First-time visitors', 'Conventions', 'Families', 'Downtown'],
    address: '250 Rep. John Lewis Way S, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Spa', 'Fitness center', 'Multiple dining options'],
    parkingNote: 'Paid downtown parking and valet are available; confirm current pricing before arrival.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for the Country Music Hall of Fame, Music City Center, Bridgestone Arena and Broadway.',
    nearbyAttractions: ['Country Music Hall of Fame', 'Music City Center', 'Bridgestone Arena', 'Lower Broadway'],
    mapQuery: 'Omni Nashville Hotel, Nashville, TN',
    relatedSlugs: ['the-joseph-nashville', 'four-seasons-hotel-nashville', 'jw-marriott-nashville'],
  }),
  realHotel({
    slug: 'jw-marriott-nashville',
    title: 'JW Marriott Nashville',
    summary: 'A high-rise luxury hotel just south of Broadway with skyline views, a rooftop pool and easy arena access.',
    whyWeRecommend: 'A reliable luxury downtown choice for travelers who want the energy of Broadway nearby without sleeping directly on it.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$$',
    bestFor: ['Luxury', 'Business travel', 'Couples', 'Arena events'],
    address: '201 8th Ave S, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Spa', 'Fitness center', 'On-site dining'],
    parkingNote: 'Paid valet/garage parking; confirm current nightly pricing.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Strong downtown position near Bridgestone Arena, the convention center and Lower Broadway.',
    nearbyAttractions: ['Bridgestone Arena', 'Music City Center', 'Lower Broadway', 'Nashville Yards'],
    mapQuery: 'JW Marriott Nashville, Nashville, TN',
    relatedSlugs: ['1-hotel-nashville', 'grand-hyatt-nashville', 'the-joseph-nashville'],
  }),
  realHotel({
    slug: 'grand-hyatt-nashville',
    title: 'Grand Hyatt Nashville',
    summary: 'A large upscale hotel at Nashville Yards on Broadway, positioned between downtown and the West End/Midtown corridor.',
    whyWeRecommend: 'Good for travelers who want a full-service hotel, a rooftop pool and quick access to both Broadway and the growing Nashville Yards district.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$$',
    bestFor: ['Business travel', 'Luxury', 'Groups', 'Nashville Yards'],
    address: '1000 Broadway, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Spa', 'Fitness center', 'On-site dining'],
    parkingNote: 'Paid downtown parking; confirm current valet and self-parking rates.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Walkable to Nashville Yards, the Gulch and Lower Broadway, though the far east end of Broadway is a longer walk.',
    nearbyAttractions: ['Nashville Yards', 'The Gulch', 'Lower Broadway', 'Frist Art Museum'],
    mapQuery: 'Grand Hyatt Nashville, Nashville, TN',
    relatedSlugs: ['1-hotel-nashville', 'jw-marriott-nashville', 'conrad-nashville'],
  }),
  realHotel({
    slug: 'holston-house-nashville',
    title: 'Holston House Nashville - The Unbound Collection by Hyatt',
    summary: 'An art-deco-influenced boutique hotel a short walk from Lower Broadway with a rooftop pool and bar.',
    whyWeRecommend: 'A smaller-scale downtown alternative to the big convention hotels, especially good when you want to walk everywhere but still have a proper rooftop.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$',
    bestFor: ['Couples', 'Boutique stays', 'Broadway', 'Rooftop pool'],
    address: '118 7th Ave N, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Rooftop bar', 'Fitness center', 'On-site dining'],
    parkingNote: 'Paid downtown parking/valet; confirm current rates.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for Lower Broadway, the Ryman, Bridgestone Arena and downtown restaurants.',
    nearbyAttractions: ['Ryman Auditorium', 'Lower Broadway', 'Bridgestone Arena', 'Fifth + Broadway'],
    mapQuery: 'Holston House Nashville, Nashville, TN',
    relatedSlugs: ['the-hermitage-hotel', 'cambria-hotel-nashville-downtown', 'drury-plaza-hotel-nashville-downtown'],
  }),
  realHotel({
    slug: 'the-hermitage-hotel',
    title: 'The Hermitage Hotel',
    summary: 'Nashville’s historic luxury hotel near the State Capitol, with a quieter position several blocks north of Lower Broadway.',
    whyWeRecommend: 'The choice for traditional luxury and history rather than a rooftop-party atmosphere. It feels distinctly Nashville without being built around nightlife.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$$',
    bestFor: ['Historic hotels', 'Luxury', 'Couples', 'Quiet downtown'],
    address: '231 6th Ave N, Nashville, TN 37219',
    amenities: ['On-site dining', 'Fitness center', 'Concierge', 'Pet-friendly rooms'],
    parkingNote: 'Valet/paid parking; confirm current pricing with the hotel.',
    hasPool: false,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Strong for the Capitol, Ryman and downtown; Broadway is walkable but not directly outside the door.',
    nearbyAttractions: ['Tennessee State Capitol', 'Ryman Auditorium', 'Fifth + Broadway', 'Bicentennial Capitol Mall'],
    mapQuery: 'The Hermitage Hotel Nashville, Nashville, TN',
    relatedSlugs: ['holston-house-nashville', 'four-seasons-hotel-nashville', 'germantown-inn'],
  }),
  realHotel({
    slug: 'drury-plaza-hotel-nashville-downtown',
    title: 'Drury Plaza Hotel Nashville Downtown',
    summary: 'A practical full-service downtown hotel in SoBro with breakfast and easy access to the convention center and Broadway.',
    whyWeRecommend: 'One of the better value plays inside the downtown core, especially for families and travelers who prioritize useful inclusions over boutique design.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$',
    bestFor: ['Value', 'Families', 'Conventions', 'First-time visitors'],
    address: '300 Korean Veterans Blvd, Nashville, TN 37201',
    amenities: ['Breakfast', 'Pool', 'Fitness center', 'On-site dining'],
    parkingNote: 'Paid on-site downtown parking; confirm the current rate.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Very good for SoBro, Music City Center, Broadway and the riverfront.',
    nearbyAttractions: ['Music City Center', 'Country Music Hall of Fame', 'Lower Broadway', 'Ascend Amphitheater'],
    mapQuery: 'Drury Plaza Hotel Nashville Downtown, Nashville, TN',
    relatedSlugs: ['omni-nashville-hotel', 'cambria-hotel-nashville-downtown', 'holston-house-nashville'],
  }),
  realHotel({
    slug: 'cambria-hotel-nashville-downtown',
    title: 'Cambria Hotel Nashville Downtown',
    summary: 'A contemporary hotel near Bridgestone Arena with a rooftop pool and a central SoBro location.',
    whyWeRecommend: 'A strong middle-ground option when you want a downtown pool and easy Broadway access without paying top-tier luxury rates.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$',
    bestFor: ['Groups', 'Arena events', 'Rooftop pool', 'Downtown'],
    address: '118 8th Ave S, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Fitness center', 'Bar', 'On-site dining'],
    parkingNote: 'Paid downtown parking/valet; confirm current rates.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for Bridgestone Arena, the convention center and Lower Broadway.',
    nearbyAttractions: ['Bridgestone Arena', 'Lower Broadway', 'Music City Center', 'Nashville Yards'],
    mapQuery: 'Cambria Hotel Nashville Downtown, Nashville, TN',
    relatedSlugs: ['drury-plaza-hotel-nashville-downtown', 'holston-house-nashville', '1-hotel-nashville'],
  }),
  realHotel({
    slug: 'thompson-nashville',
    title: 'Thompson Nashville, by Hyatt',
    summary: 'A design-forward hotel in the heart of the Gulch with a popular rooftop bar and street-level dining.',
    whyWeRecommend: 'Still one of the most natural fits for a stylish Gulch weekend: you can walk to restaurants and Station Inn, then reach Broadway without staying on Broadway.',
    neighborhood: 'the-gulch',
    priceCategory: '$$$$',
    bestFor: ['Couples', 'The Gulch', 'Food and drink', 'Design'],
    address: '401 11th Ave S, Nashville, TN 37203',
    amenities: ['Rooftop bar', 'Fitness center', 'On-site dining', 'Coffee shop'],
    parkingNote: 'Valet/paid parking; nearby Gulch garages provide alternatives.',
    hasPool: false,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent inside the Gulch and roughly a 15-20 minute walk to Lower Broadway.',
    nearbyAttractions: ['Station Inn', 'The Gulch', 'Nashville Yards', 'Lower Broadway'],
    mapQuery: 'Thompson Nashville, Nashville, TN',
    relatedSlugs: ['w-nashville', '1-hotel-nashville', 'grand-hyatt-nashville'],
  }),
  realHotel({
    slug: 'w-nashville',
    title: 'W Nashville',
    summary: 'A large lifestyle hotel in the Gulch with a rooftop pool, multiple food-and-drink concepts and an active social scene.',
    whyWeRecommend: 'The better Gulch fit for groups who want the hotel to be part of the weekend rather than simply a place to sleep.',
    neighborhood: 'the-gulch',
    priceCategory: '$$$$',
    bestFor: ['Groups', 'The Gulch', 'Pool weekends', 'Nightlife'],
    address: '300 12th Ave S, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Fitness center', 'Multiple dining options', 'Bars'],
    parkingNote: 'Valet/paid parking; self-parking garages are available around the Gulch.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for the Gulch, with downtown and Nashville Yards close enough to walk for most visitors.',
    nearbyAttractions: ['The Gulch', 'Station Inn', 'Nashville Yards', 'Lower Broadway'],
    mapQuery: 'W Nashville, Nashville, TN',
    relatedSlugs: ['thompson-nashville', '1-hotel-nashville', 'grand-hyatt-nashville'],
  }),
  realHotel({
    slug: 'conrad-nashville',
    title: 'Conrad Nashville',
    summary: 'A modern luxury hotel on West End near Music Row, with a rooftop pool terrace and a quieter setting than Lower Broadway.',
    whyWeRecommend: 'A strong upscale choice for travelers who want luxury and a pool without committing to the downtown party zone.',
    neighborhood: 'midtown',
    priceCategory: '$$$$',
    bestFor: ['Luxury', 'Couples', 'Music Row', 'Pool'],
    address: '1620 West End Ave, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Fitness center', 'On-site dining', 'Concierge'],
    parkingNote: 'Paid self-parking and valet are available; confirm current rates.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Good for Music Row and Midtown; Broadway is a short ride or a longer walk.',
    nearbyAttractions: ['Music Row', 'Midtown', 'Vanderbilt University', 'Nashville Yards'],
    mapQuery: 'Conrad Nashville, Nashville, TN',
    relatedSlugs: ['graduate-nashville', 'virgin-hotels-nashville', 'hutton-hotel'],
  }),
  realHotel({
    slug: 'graduate-nashville',
    title: 'Graduate by Hilton Nashville',
    summary: 'A playful, highly themed hotel near Vanderbilt and Music Row with a rooftop restaurant and pool scene.',
    whyWeRecommend: 'A memorable alternative to the polished downtown towers, especially for younger groups and repeat visitors who want Midtown energy.',
    neighborhood: 'midtown',
    priceCategory: '$$$',
    bestFor: ['Groups', 'Design', 'Vanderbilt', 'Rooftop'],
    address: '101 20th Ave N, Nashville, TN 37203',
    amenities: ['Rooftop', 'Pool', 'Fitness center', 'On-site dining'],
    parkingNote: 'Paid hotel parking; confirm current self-park/valet options.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for Vanderbilt and nearby Midtown/Music Row; downtown is a short ride.',
    nearbyAttractions: ['Vanderbilt University', 'Music Row', 'Midtown', 'Centennial Park'],
    mapQuery: 'Graduate Nashville, Nashville, TN',
    relatedSlugs: ['conrad-nashville', 'hutton-hotel', 'loews-vanderbilt-hotel'],
  }),
  realHotel({
    slug: 'virgin-hotels-nashville',
    title: 'Virgin Hotels Nashville',
    summary: 'A lively Music Row hotel with a rooftop pool, restaurants and a nightlife-forward personality.',
    whyWeRecommend: 'Best when you want Music Row location and a social hotel rather than a traditional business-hotel feel.',
    neighborhood: 'midtown',
    priceCategory: '$$$',
    bestFor: ['Groups', 'Music Row', 'Pool weekends', 'Nightlife'],
    address: '1 Music Square W, Nashville, TN 37203',
    amenities: ['Rooftop pool', 'Fitness center', 'On-site dining', 'Bars'],
    parkingNote: 'Paid parking/valet; confirm current rates.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Very good for Music Row and Midtown; Broadway is reachable by a longer walk or short ride.',
    nearbyAttractions: ['Music Row', 'Midtown', 'The Gulch', 'Vanderbilt University'],
    mapQuery: 'Virgin Hotels Nashville, Nashville, TN',
    relatedSlugs: ['conrad-nashville', 'graduate-nashville', 'hutton-hotel'],
  }),
  realHotel({
    slug: 'hutton-hotel',
    title: 'Hutton Hotel',
    summary: 'A music-focused boutique hotel on West End with an intimate live-music venue and songwriter studios.',
    whyWeRecommend: 'A good repeat-visitor option when Music Row and Nashville’s creative side matter more than walking straight onto Broadway.',
    neighborhood: 'midtown',
    priceCategory: '$$$',
    bestFor: ['Music-focused trips', 'Couples', 'Business travel', 'Midtown'],
    address: '1808 West End Ave, Nashville, TN 37203',
    amenities: ['Fitness center', 'Live music venue', 'Writers studios', 'On-site food and drink'],
    parkingNote: 'Paid hotel parking/valet; confirm current rates.',
    hasPool: false,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Good for Midtown, Music Row and Vanderbilt; downtown is usually easier by rideshare.',
    nearbyAttractions: ['Music Row', 'Vanderbilt University', 'Midtown', 'Centennial Park'],
    mapQuery: 'Hutton Hotel Nashville, Nashville, TN',
    relatedSlugs: ['conrad-nashville', 'graduate-nashville', 'loews-vanderbilt-hotel'],
  }),
  realHotel({
    slug: 'loews-vanderbilt-hotel',
    title: 'Loews Vanderbilt Hotel',
    summary: 'A long-running full-service hotel on West End across from Vanderbilt, with easy access to Midtown and Music Row.',
    whyWeRecommend: 'One of the most dependable choices for Vanderbilt visits, business travel and families who do not need to stay in the Broadway core.',
    neighborhood: 'midtown',
    priceCategory: '$$$',
    bestFor: ['Vanderbilt', 'Families', 'Business travel', 'Midtown'],
    address: '2100 West End Ave, Nashville, TN 37203',
    amenities: ['Fitness center', 'On-site dining', 'Meeting space', 'Pet-friendly rooms'],
    parkingNote: 'Paid on-site parking/valet; confirm current rates.',
    hasPool: false,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for Vanderbilt and Midtown; Centennial Park is close and Broadway is a short ride.',
    nearbyAttractions: ['Vanderbilt University', 'Centennial Park', 'The Parthenon', 'Music Row'],
    mapQuery: 'Loews Vanderbilt Hotel Nashville, Nashville, TN',
    relatedSlugs: ['graduate-nashville', 'hutton-hotel', 'holiday-inn-nashville-vanderbilt'],
  }),
  realHotel({
    slug: 'holiday-inn-nashville-vanderbilt',
    title: 'Holiday Inn Nashville-Vanderbilt (Dwtn) by IHG',
    summary: 'A practical West End hotel directly across from Centennial Park, with a seasonal pool and strong Vanderbilt access.',
    whyWeRecommend: 'A sensible value option for families, Vanderbilt trips and travelers who would rather spend on the city than on a luxury room.',
    neighborhood: 'midtown',
    priceCategory: '$$',
    bestFor: ['Value', 'Families', 'Vanderbilt', 'Centennial Park'],
    address: '2613 West End Ave, Nashville, TN 37203',
    amenities: ['Seasonal pool', 'Fitness center', 'On-site dining', 'Area shuttle'],
    parkingNote: 'On-site parking is available; confirm the current nightly charge.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Excellent for Centennial Park and Vanderbilt; downtown is best reached by a short ride.',
    nearbyAttractions: ['Centennial Park', 'The Parthenon', 'Vanderbilt University', 'West End'],
    mapQuery: 'Holiday Inn Nashville Vanderbilt, Nashville, TN',
    relatedSlugs: ['loews-vanderbilt-hotel', 'graduate-nashville', 'hutton-hotel'],
  }),
  realHotel({
    slug: 'germantown-inn',
    title: 'Germantown Inn',
    summary: 'A small boutique inn in historic Germantown, set apart from the larger downtown hotel towers.',
    whyWeRecommend: 'The best fit in this list for travelers who care more about neighborhood restaurants and quiet residential character than big-hotel amenities.',
    neighborhood: 'germantown',
    priceCategory: '$$$',
    bestFor: ['Couples', 'Boutique stays', 'Food-focused trips', 'Quiet stays'],
    address: '1218 6th Ave N, Nashville, TN 37208',
    amenities: ['Breakfast', 'Courtyard and common areas', 'Boutique rooms', 'Neighborhood setting'],
    parkingNote: 'Confirm current on-site/street parking arrangements with the inn before arrival.',
    hasPool: false,
    hasFitness: false,
    familyFriendly: true,
    walkabilityNote: 'Excellent for Germantown restaurants, Bicentennial Capitol Mall and the Farmers Market; Lower Broadway is farther south.',
    nearbyAttractions: ['Nashville Farmers Market', 'Bicentennial Capitol Mall', 'First Horizon Park', 'Tennessee State Capitol'],
    mapQuery: 'Germantown Inn Nashville, Nashville, TN',
    relatedSlugs: ['the-hermitage-hotel', 'grand-hyatt-nashville', 'omni-nashville-hotel'],
  }),
  realHotel({
    slug: 'hilton-nashville-green-hills',
    title: 'Hilton Nashville Green Hills',
    summary: 'A modern full-service hotel in Green Hills with a rooftop pool and convenient access to shopping and the Bluebird Cafe.',
    whyWeRecommend: 'A useful option for travelers who want Green Hills, easy parking access and a quieter base away from downtown nightlife.',
    neighborhood: 'green-hills',
    priceCategory: '$$$',
    bestFor: ['Shopping', 'Business travel', 'Quiet stays', 'Green Hills'],
    address: '3801 Cleghorn Ave, Nashville, TN 37215',
    amenities: ['Rooftop pool', 'Fitness center', 'On-site dining', 'Meeting space'],
    parkingNote: 'On-site parking is available; confirm current pricing.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote: 'Walkable to Green Hills shopping and nearby restaurants; downtown requires a drive or rideshare.',
    nearbyAttractions: ['The Mall at Green Hills', 'Bluebird Cafe', 'Green Hills restaurants', 'Radnor Lake'],
    mapQuery: 'Hilton Nashville Green Hills, Nashville, TN',
    relatedSlugs: ['loews-vanderbilt-hotel', 'holiday-inn-nashville-vanderbilt', 'germantown-inn'],
  }),
];

export function getHotel(slug: string): Hotel | undefined {
  return hotels.find((hotel) => hotel.slug === slug);
}
