import type { Restaurant, Hotel, NashvilleEvent, Venue, Attraction, Listing } from '../types';

/**
 * Listing data for the template.
 *
 * Nothing in this file has been verified against a primary source. Restaurants
 * and hotels use bracketed sample names on purpose so no real business is
 * described with details we have not checked. Real Nashville institutions
 * appear by name only where the description stays at the level of widely known
 * general character, and their practical fields are placeholders.
 *
 * Before launch: replace every record, confirm the details, and move
 * `dataStatus` to 'verified' one listing at a time.
 */

const DEMO_SOURCE_NOTE = 'Demo record. Replace with a verified listing before launch.';
const INSTITUTION_SOURCE_NOTE =
  'Real venue, placeholder practicals. Confirm address, hours, and pricing with the operator before publishing.';

/* ---------------------------------- Restaurants ---------------------------------- */

export const restaurants: Restaurant[] = [
  {
    kind: 'restaurant',
    slug: 'sample-germantown-chophouse',
    title: '[Sample] Germantown Chophouse',
    summary: 'A sample record for a reservation-driven steakhouse in the middle of Germantown.',
    whyWeRecommend:
      'Stands in for the kind of room you book three weeks out for a birthday or a closing dinner. The tradeoff is noise. The dining room runs loud after 7pm, so it suits a celebration better than a conversation.',
    cuisine: 'Steakhouse',
    neighborhood: 'germantown',
    priceRange: '$$$$',
    bestFor: ['Anniversaries', 'Client dinners', 'Groups of 6+'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    reservationPlatform: '[Reservation platform — verify]',
    mapQuery: 'Germantown, Nashville, TN',
    parkingNote:
      'Street parking on the brick blocks fills by 6pm. Park two streets north and walk five minutes instead of circling.',
    dressCode: 'Collared shirts and dresses are common. Nobody will turn you away in jeans.',
    goodForGroups: true,
    outdoorSeating: false,
    relatedSlugs: ['sample-gulch-pasta-bar', 'sample-germantown-boutique-hotel', 'nashville-farmers-market'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    dateUpdated: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'restaurant',
    slug: 'sample-east-side-fish-counter',
    title: '[Sample] East Side Fish Counter',
    summary: 'A sample record for a small counter-service seafood spot in East Nashville.',
    whyWeRecommend:
      'Represents the walk-up, order-at-the-window format that East Nashville does well. Seating is limited, so it works better for two people than for a group that wants to sit together.',
    cuisine: 'Seafood',
    neighborhood: 'east-nashville',
    priceRange: '$$',
    bestFor: ['Solo travelers', 'Quick lunch', 'Couples'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    mapQuery: 'East Nashville, Nashville, TN',
    parkingNote: 'Free street parking on the side streets. Read the residential permit signs before you leave the car.',
    dressCode: 'No dress code. Counter service.',
    goodForGroups: false,
    outdoorSeating: true,
    relatedSlugs: ['sample-east-nashville-inn', 'shelby-bottoms-greenway', 'sample-east-nashville-listening-room'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'restaurant',
    slug: 'sample-midtown-hot-chicken-counter',
    title: '[Sample] Midtown Hot Chicken Counter',
    summary: 'A sample record for a hot chicken counter near Music Row.',
    whyWeRecommend:
      'Placeholder for the hot chicken stop most first-time visitors want to make. Order one heat level below what you think you can handle. The heat builds for several minutes after the first bite.',
    cuisine: 'Hot chicken',
    neighborhood: 'midtown',
    priceRange: '$',
    bestFor: ['First-time visitors', 'Quick lunch', 'Late dinner'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    mapQuery: 'Midtown, Nashville, TN',
    parkingNote: 'Small shared lot that turns over fast. A garage two blocks east is the reliable fallback.',
    dressCode: 'None. Wear something you do not mind getting grease on.',
    goodForGroups: true,
    outdoorSeating: true,
    relatedSlugs: ['sample-midtown-value-hotel', 'the-parthenon', 'sample-hillsboro-village-diner'],
    dataStatus: 'unverified',
    dateChecked: '2026-07-28',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'restaurant',
    slug: 'sample-12-south-brunch-room',
    title: '[Sample] 12 South Brunch Room',
    summary: 'A sample record for a weekend brunch room on the 12 South strip.',
    whyWeRecommend:
      'Models the brunch format that drives 12 South weekend traffic. Good for a slow morning before shopping. The honest caveat is the wait, which routinely runs past an hour after 10am on Saturdays.',
    cuisine: 'American brunch',
    neighborhood: '12-south',
    priceRange: '$$',
    bestFor: ['Weekend brunch', 'Couples', 'Groups of 4'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    reservationPlatform: '[Reservation platform — verify]',
    mapQuery: '12 South, Nashville, TN',
    parkingNote: 'Street parking only and it is contested on weekends. Arrive before 9:30am or plan on a rideshare.',
    dressCode: 'Casual.',
    goodForGroups: true,
    outdoorSeating: true,
    relatedSlugs: ['sample-12-south-guesthouse', 'sample-12-south-walking-loop', 'sample-green-hills-sushi-counter'],
    dataStatus: 'needs-recheck',
    dateChecked: '2026-07-28',
    dateUpdated: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'restaurant',
    slug: 'sample-gulch-pasta-bar',
    title: '[Sample] Gulch Pasta Bar',
    summary: 'A sample record for a pasta-focused dining room in the Gulch.',
    whyWeRecommend:
      'Stands in for the walkable pre-show dinner near Station Inn and the downtown venues. Bar seating usually opens before the tables do, which helps when you have an 8pm ticket.',
    cuisine: 'Italian',
    neighborhood: 'the-gulch',
    priceRange: '$$$',
    bestFor: ['Pre-show dinner', 'Couples', 'Solo travelers'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    reservationPlatform: '[Reservation platform — verify]',
    mapQuery: 'The Gulch, Nashville, TN',
    parkingNote: 'Garage under the building, paid by the hour. Validation is inconsistent, so budget for it.',
    dressCode: 'Smart casual. Most people come from work or a hotel.',
    goodForGroups: false,
    outdoorSeating: true,
    relatedSlugs: ['station-inn', 'sample-gulch-tower-hotel', 'sample-germantown-chophouse'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'restaurant',
    slug: 'sample-sylvan-park-meat-and-three',
    title: '[Sample] Sylvan Park Meat-and-Three',
    summary: 'A sample record for a weekday meat-and-three on the west side.',
    whyWeRecommend:
      'Placeholder for the lunch format that predates every recent food trend here. You pick a meat and three sides from a board. It is the cheapest sit-down meal in this file and the one most likely to close by mid-afternoon.',
    cuisine: 'Southern',
    neighborhood: 'sylvan-park',
    priceRange: '$',
    bestFor: ['Weekday lunch', 'Families', 'Budget meals'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    mapQuery: 'Sylvan Park, Nashville, TN',
    parkingNote: 'Free street parking, usually available within a block.',
    dressCode: 'None.',
    goodForGroups: true,
    outdoorSeating: false,
    relatedSlugs: ['sample-sylvan-park-greenway-loop', 'sample-hillsboro-village-diner'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'restaurant',
    slug: 'sample-weho-taqueria',
    title: '[Sample] Wedgewood-Houston Taqueria',
    summary: 'A sample record for a taqueria in a converted warehouse space south of downtown.',
    whyWeRecommend:
      'Fits the art-crawl evening: eat first, then walk the galleries. The room is loud and the tables are shared, so it suits a group that does not mind sitting close to strangers.',
    cuisine: 'Mexican',
    neighborhood: 'wedgewood-houston',
    priceRange: '$$',
    bestFor: ['Groups of 6+', 'Before a gallery walk', 'Late dinner'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    mapQuery: 'Wedgewood-Houston, Nashville, TN',
    parkingNote: 'Free lot and street parking most nights. Art crawl Saturdays are the exception; come early.',
    dressCode: 'Casual.',
    goodForGroups: true,
    outdoorSeating: true,
    relatedSlugs: ['sample-weho-gallery-walk', 'sample-weho-warehouse-hotel', 'sample-weho-art-crawl'],
    dataStatus: 'unverified',
    dateChecked: '2026-07-28',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'restaurant',
    slug: 'sample-hillsboro-village-diner',
    title: '[Sample] Hillsboro Village Diner',
    summary: 'A sample record for an all-day diner on the Hillsboro Village strip.',
    whyWeRecommend:
      'Represents the everyday room that a college neighborhood needs. Booths, breakfast served past noon, and a check that stays under twenty dollars. Not a destination meal.',
    cuisine: 'Diner',
    neighborhood: 'hillsboro-village',
    priceRange: '$',
    bestFor: ['Solo travelers', 'Breakfast', 'Budget meals'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    mapQuery: 'Hillsboro Village, Nashville, TN',
    parkingNote: 'Metered street parking plus a small garage. Tightest when Vanderbilt is in session.',
    dressCode: 'None.',
    goodForGroups: false,
    outdoorSeating: false,
    relatedSlugs: ['sample-hillsboro-village-cinema', 'the-parthenon', 'sample-12-south-brunch-room'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'restaurant',
    slug: 'sample-green-hills-sushi-counter',
    title: '[Sample] Green Hills Sushi Counter',
    summary: 'A sample record for a twelve-seat sushi counter south of the city.',
    whyWeRecommend:
      'Built to show how a small-format tasting counter should render on this site. Two seatings a night and no substitutions. Skip it if anyone in your party is a picky eater.',
    cuisine: 'Japanese',
    neighborhood: 'green-hills',
    priceRange: '$$$$',
    bestFor: ['Couples', 'Solo travelers', 'Special occasions'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    reservationPlatform: '[Reservation platform — verify]',
    mapQuery: 'Green Hills, Nashville, TN',
    parkingNote: 'Free lot parking. Hillsboro Pike traffic is the real cost; leave fifteen minutes early.',
    dressCode: 'Smart casual.',
    goodForGroups: false,
    outdoorSeating: false,
    relatedSlugs: ['bluebird-cafe', 'sample-green-hills-suites', 'sample-12-south-brunch-room'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    dateUpdated: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'restaurant',
    slug: 'sample-broadway-barbecue-hall',
    title: '[Sample] Broadway Barbecue Hall',
    summary: 'A sample record for a large barbecue hall a block off Lower Broadway.',
    whyWeRecommend:
      'Sized for the group that cannot get a reservation anywhere else downtown. Long tables, order at the counter, seat yourself. Quality in this format is usually a step below the pits outside the tourist core.',
    cuisine: 'Barbecue',
    neighborhood: 'downtown-broadway',
    priceRange: '$$',
    bestFor: ['Groups of 6+', 'Bachelor and bachelorette parties', 'Late dinner'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    mapQuery: 'Lower Broadway, Nashville, TN',
    parkingNote: 'Use a garage and expect event-night rates. Street parking downtown is enforced aggressively.',
    dressCode: 'None.',
    goodForGroups: true,
    outdoorSeating: true,
    relatedSlugs: ['ryman-auditorium', 'country-music-hall-of-fame', 'sample-broadway-high-rise-hotel'],
    dataStatus: 'unverified',
    dateChecked: '2026-07-28',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'restaurant',
    slug: 'sample-germantown-wine-bar',
    title: '[Sample] Germantown Wine Bar',
    summary: 'A sample record for a small wine bar with a short food menu near the farmers market.',
    whyWeRecommend:
      'Useful as a second stop after dinner when you want a quieter room than Broadway. Seating is limited and walk-ins after 8pm usually wait standing.',
    cuisine: 'Wine bar',
    neighborhood: 'germantown',
    priceRange: '$$$',
    bestFor: ['Couples', 'After-dinner drinks', 'Small groups'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    reservationPlatform: '[Reservation platform — verify]',
    mapQuery: 'Germantown, Nashville, TN',
    parkingNote: 'Street parking nearby. Market nights fill the free lot first.',
    dressCode: 'Smart casual.',
    goodForGroups: false,
    outdoorSeating: true,
    relatedSlugs: ['sample-germantown-chophouse', 'sample-germantown-boutique-hotel', 'nashville-farmers-market'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-04',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'restaurant',
    slug: 'sample-midtown-late-kitchen',
    title: '[Sample] Midtown Late Kitchen',
    summary: 'A sample record for a kitchen that stays open after most Midtown restaurants close.',
    whyWeRecommend:
      'Built for the post-show crowd coming back from Broadway or Music Row. Food is better than a hotel lobby, quieter than a honky-tonk, and service slows after midnight.',
    cuisine: 'American',
    neighborhood: 'midtown',
    priceRange: '$$',
    bestFor: ['Late dinner', 'After a show', 'Groups of 4'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    mapQuery: 'Midtown, Nashville, TN',
    parkingNote: 'Paid lot next door. Street meters end earlier than the kitchen does.',
    dressCode: 'Casual.',
    goodForGroups: true,
    outdoorSeating: false,
    relatedSlugs: ['sample-midtown-value-hotel', 'sample-midtown-hot-chicken-counter', 'the-parthenon'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-04',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'restaurant',
    slug: 'sample-east-nashville-patio-cafe',
    title: '[Sample] East Nashville Patio Cafe',
    summary: 'A sample record for a daytime cafe with a large patio near Five Points.',
    whyWeRecommend:
      'A slow morning option before you commit to the rest of East Nashville. Coffee and a short food menu; not a dinner destination. Patio seats go first on warm weekends.',
    cuisine: 'Cafe',
    neighborhood: 'east-nashville',
    priceRange: '$',
    bestFor: ['Breakfast', 'Remote work', 'Solo travelers'],
    address: '[Address — verify]',
    hoursNote: '[Verify current hours]',
    mapQuery: 'Five Points, East Nashville, TN',
    parkingNote: 'Street parking within two blocks. Avoid blocking driveways on residential streets.',
    dressCode: 'None.',
    goodForGroups: false,
    outdoorSeating: true,
    relatedSlugs: ['sample-east-side-fish-counter', 'sample-east-nashville-inn', 'shelby-bottoms-greenway'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-04',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
];

/* ------------------------------------ Hotels ------------------------------------- */

export const hotels: Hotel[] = [
  {
    kind: 'hotel',
    slug: 'sample-germantown-boutique-hotel',
    title: '[Sample] Germantown Boutique Hotel',
    summary: 'A sample record for a small hotel on the quiet side of Germantown.',
    whyWeRecommend:
      'The case for staying here is dinner. You can walk to most of the neighborhood restaurants and still reach downtown in twenty minutes on foot. Rooms in this format tend to be small.',
    neighborhood: 'germantown',
    priceCategory: '$$$',
    bestFor: ['Couples', 'Food-focused trips', 'Quiet stays'],
    address: '[Address — verify]',
    amenities: ['On-site bar', 'Room service', 'Bike storage', 'Pet friendly'],
    parkingNote: 'Valet only in this part of Germantown. Street parking exists but turns over slowly on game nights.',
    hasPool: false,
    hasFitness: true,
    familyFriendly: false,
    walkabilityNote:
      'Strong on foot. Restaurants, the farmers market, and the capitol grounds are all within fifteen minutes walking. Downtown is about twenty.',
    nearbyAttractions: ['Nashville Farmers\' Market', 'Bicentennial Capitol Mall', 'Downtown Nashville'],
    mapQuery: 'Germantown, Nashville, TN',
    relatedSlugs: ['sample-germantown-chophouse', 'nashville-farmers-market', 'sample-broadway-high-rise-hotel'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    dateUpdated: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'hotel',
    slug: 'sample-gulch-tower-hotel',
    title: '[Sample] Gulch Tower Hotel',
    summary: 'A sample record for a mid-rise hotel in the middle of the Gulch.',
    whyWeRecommend:
      'A demonstration of how a paid placement renders. The Gulch works well for groups who want to walk to dinner and reach Broadway in fifteen minutes without sleeping over a honky-tonk.',
    neighborhood: 'the-gulch',
    priceCategory: '$$$$',
    bestFor: ['Groups', 'Bachelorette parties', 'Walkable stays'],
    address: '[Address — verify]',
    amenities: ['Rooftop pool', 'Fitness center', 'Restaurant', 'Meeting rooms', 'Valet parking'],
    parkingNote: 'Valet in the building garage, charged nightly. Self-park garages nearby usually run cheaper.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: false,
    walkabilityNote:
      'Everything in the Gulch is within a five-minute walk. Downtown is fifteen minutes on foot along a well-lit route.',
    nearbyAttractions: ['Station Inn', 'Lower Broadway', 'Country Music Hall of Fame'],
    mapQuery: 'The Gulch, Nashville, TN',
    relatedSlugs: ['sample-gulch-pasta-bar', 'station-inn', 'sample-broadway-high-rise-hotel'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'sponsored',
    sponsorName: '[Sponsor Name]',
  },
  {
    kind: 'hotel',
    slug: 'sample-broadway-high-rise-hotel',
    title: '[Sample] Broadway High-Rise Hotel',
    summary: 'A sample record for a large downtown hotel two blocks off Lower Broadway.',
    whyWeRecommend:
      'The trade downtown is convenience for quiet. You can walk to every venue in this file that sits downtown. Ask for a room on a high floor facing away from Broadway if you plan to sleep before 1am.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$',
    bestFor: ['First-time visitors', 'Short trips', 'Groups'],
    address: '[Address — verify]',
    amenities: ['Fitness center', 'Rooftop bar', 'Business center', 'Laundry service'],
    parkingNote: 'Garage parking with a nightly fee. Rates climb on arena event nights, so check before you book a car.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote:
      'The strongest walking position in the city. The Ryman, the Hall of Fame, the arena, and the honky-tonks are all under ten minutes on foot.',
    nearbyAttractions: ['Ryman Auditorium', 'Country Music Hall of Fame', 'Bridgestone Arena'],
    mapQuery: 'Lower Broadway, Nashville, TN',
    relatedSlugs: ['ryman-auditorium', 'country-music-hall-of-fame', 'sample-broadway-barbecue-hall'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'sample-east-nashville-inn',
    title: '[Sample] East Nashville Inn',
    summary: 'A sample record for a small inn on a residential block in East Nashville.',
    whyWeRecommend:
      'Suits a repeat visitor who would rather eat in East Nashville than walk Broadway. Plan on driving or riding to most things, because the neighborhood clusters are spread out.',
    neighborhood: 'east-nashville',
    priceCategory: '$$',
    bestFor: ['Repeat visitors', 'Couples', 'Longer stays'],
    address: '[Address — verify]',
    amenities: ['Free breakfast', 'Courtyard', 'Pet friendly', 'Free parking'],
    parkingNote: 'Free on-site spaces plus street parking. Easier here than anywhere downtown.',
    hasPool: false,
    hasFitness: false,
    familyFriendly: true,
    walkabilityNote:
      'Good within the immediate Five Points area. Getting to other East Nashville clusters means a short drive or a ten-minute ride.',
    nearbyAttractions: ['Shelby Bottoms Greenway', 'Five Points', 'Downtown Nashville'],
    mapQuery: 'East Nashville, Nashville, TN',
    relatedSlugs: ['sample-east-side-fish-counter', 'shelby-bottoms-greenway', 'sample-east-nashville-listening-room'],
    dataStatus: 'unverified',
    dateChecked: '2026-07-28',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'sample-midtown-value-hotel',
    title: '[Sample] Midtown Value Hotel',
    summary: 'A sample record for a mid-priced hotel near Music Row.',
    whyWeRecommend:
      'The value play. You give up the downtown address and get a shorter bill, plus a five-minute ride to Broadway. Rooms near the elevator bank in this class tend to be noisy.',
    neighborhood: 'midtown',
    priceCategory: '$$',
    bestFor: ['Budget trips', 'Business travel', 'Younger nightlife'],
    address: '[Address — verify]',
    amenities: ['Fitness center', 'Free breakfast', 'Coin laundry', 'Airport shuttle'],
    parkingNote: 'Self-park lot with a modest nightly charge. Fills during Vanderbilt events.',
    hasPool: false,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote:
      'Walkable to Music Row and the Midtown bars. Downtown is about twenty-five minutes on foot, which most people skip in favor of a ride.',
    nearbyAttractions: ['Music Row', 'The Parthenon', 'Vanderbilt campus'],
    mapQuery: 'Midtown, Nashville, TN',
    relatedSlugs: ['sample-midtown-hot-chicken-counter', 'the-parthenon', 'sample-hillsboro-village-cinema'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'hotel',
    slug: 'sample-12-south-guesthouse',
    title: '[Sample] 12 South Guesthouse',
    summary: 'A sample record for a small guesthouse a block off the 12 South strip.',
    whyWeRecommend:
      'Quiet, residential, and close enough to walk the whole strip. Best for a couple who wants coffee and shopping in the morning without moving the car. There is no front desk after hours in this format.',
    neighborhood: '12-south',
    priceCategory: '$$$',
    bestFor: ['Couples', 'Quiet stays', 'Walkable afternoons'],
    address: '[Address — verify]',
    amenities: ['Kitchenette', 'Porch seating', 'Self check-in', 'Free parking'],
    parkingNote: 'One reserved space per room. Street parking around it is residential and posted.',
    hasPool: false,
    hasFitness: false,
    familyFriendly: false,
    walkabilityNote:
      'The 12 South strip is a five-minute walk. Sevier Park is ten. Everything else needs a car or a ride.',
    nearbyAttractions: ['12 South strip', 'Sevier Park', 'Belmont area'],
    mapQuery: '12 South, Nashville, TN',
    relatedSlugs: ['sample-12-south-brunch-room', 'sample-12-south-walking-loop', 'sample-green-hills-suites'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'hotel',
    slug: 'sample-green-hills-suites',
    title: '[Sample] Green Hills Suites',
    summary: 'A sample record for an all-suite hotel near the Green Hills shopping district.',
    whyWeRecommend:
      'Two-room suites and free parking make this the family option in this file. The cost is distance. Everything downtown is fifteen to twenty-five minutes away depending on Hillsboro Pike traffic.',
    neighborhood: 'green-hills',
    priceCategory: '$$',
    bestFor: ['Families', 'Longer stays', 'Shopping trips'],
    address: '[Address — verify]',
    amenities: ['Indoor pool', 'Fitness center', 'Free breakfast', 'In-suite kitchen', 'Free parking'],
    parkingNote: 'Free surface lot. The easiest parking of any hotel here.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote:
      'Walkable to the mall and nearby restaurants. Not walkable to anything else. Budget for rides or bring a car.',
    nearbyAttractions: ['Bluebird Cafe', 'Green Hills shopping', 'Radnor Lake'],
    mapQuery: 'Green Hills, Nashville, TN',
    relatedSlugs: ['bluebird-cafe', 'sample-green-hills-sushi-counter', 'sample-12-south-guesthouse'],
    dataStatus: 'unverified',
    dateChecked: '2026-07-28',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'hotel',
    slug: 'sample-weho-warehouse-hotel',
    title: '[Sample] Wedgewood-Houston Warehouse Hotel',
    summary: 'A sample record for a converted warehouse hotel in the arts district.',
    whyWeRecommend:
      'Fits a traveler who wants galleries and breweries over honky-tonks. Concrete floors and high ceilings mean sound carries between rooms, which is worth knowing before you book.',
    neighborhood: 'wedgewood-houston',
    priceCategory: '$$$',
    bestFor: ['Art', 'Repeat visitors', 'Avoiding crowds'],
    address: '[Address — verify]',
    amenities: ['Rooftop bar', 'Fitness center', 'Coffee bar', 'Pet friendly'],
    parkingNote: 'Free on-site lot most nights. It fills on art crawl Saturdays.',
    hasPool: false,
    hasFitness: true,
    familyFriendly: false,
    walkabilityNote:
      'Galleries and taprooms are within ten minutes on foot. Downtown is a ten-minute drive and not a walk worth making.',
    nearbyAttractions: ['Wedgewood-Houston galleries', 'Local breweries', 'Downtown Nashville'],
    mapQuery: 'Wedgewood-Houston, Nashville, TN',
    relatedSlugs: ['sample-weho-taqueria', 'sample-weho-gallery-walk', 'sample-weho-art-crawl'],
    dataStatus: 'needs-recheck',
    dateChecked: '2026-07-28',
    dateUpdated: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'hotel',
    slug: 'sample-music-valley-resort',
    title: '[Sample] Music Valley Resort',
    summary: 'A sample record for a large resort-style stay near Opryland and Music Valley.',
    whyWeRecommend:
      'The case for Music Valley is space: indoor atriums, multiple restaurants, and rooms that suit families and groups who do not need to walk to Broadway. The tradeoff is a twenty-to-thirty-minute ride downtown on traffic.',
    neighborhood: 'east-nashville',
    priceCategory: '$$$',
    bestFor: ['Families', 'Groups', 'Resort stays', 'Opry tickets'],
    address: '[Address — verify]',
    amenities: ['Indoor atrium', 'Multiple restaurants', 'Pool', 'Fitness center', 'Shuttle', 'Free parking'],
    parkingNote: 'Free self-park lots. Garage options exist for bad weather. Confirm shuttle schedules for Opry nights.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote:
      'Walkable inside the resort campus. Almost nothing off-campus is a practical walk. Budget rides for downtown and East Nashville dinners.',
    nearbyAttractions: ['Grand Ole Opry', 'Opry Mills', 'Music Valley', 'Cumberland River'],
    mapQuery: 'Music Valley, Nashville, TN',
    relatedSlugs: ['sample-green-hills-suites', 'sample-broadway-high-rise-hotel', 'sample-east-nashville-inn'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-04',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'affiliate',
  },
  {
    kind: 'hotel',
    slug: 'sample-downtown-pool-hotel',
    title: '[Sample] Downtown Pool Hotel',
    summary: 'A sample record for a mid-size downtown hotel with a rooftop pool facing the river.',
    whyWeRecommend:
      'Built for warm-weather trips and groups that want a pool without leaving the core. Rooftop seating fills on weekend afternoons; book a cabana if that is the point of the stay.',
    neighborhood: 'downtown-broadway',
    priceCategory: '$$$$',
    bestFor: ['Groups', 'Bachelorette parties', 'Summer trips', 'Pool days'],
    address: '[Address — verify]',
    amenities: ['Rooftop pool', 'Pool bar', 'Fitness center', 'Restaurant', 'Valet parking'],
    parkingNote: 'Valet in the building. Self-park garages within two blocks on non-event nights.',
    hasPool: true,
    hasFitness: true,
    familyFriendly: true,
    walkabilityNote:
      'Strong. Bridgestone, Broadway, and the riverfront parks are under ten minutes on foot.',
    nearbyAttractions: ['Lower Broadway', 'Bridgestone Arena', 'Cumberland Riverfront'],
    mapQuery: 'Downtown Nashville, TN',
    relatedSlugs: ['sample-broadway-high-rise-hotel', 'sample-broadway-barbecue-hall', 'bridgestone-arena'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-04',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'affiliate',
  },
];

/* ------------------------------------ Events ------------------------------------- */

export const events: NashvilleEvent[] = [
  {
    kind: 'event',
    slug: 'sample-fall-songwriter-round',
    title: '[Sample] Fall Songwriter Round',
    summary: 'A sample listing for an in-the-round songwriter night at the Station Inn.',
    startDate: '2026-08-08',
    timeNote: '[Verify current showtime]',
    venue: 'Station Inn',
    neighborhood: 'the-gulch',
    category: 'Concert',
    description:
      'Three or four writers trade songs and talk about how each one got made. The room is small and the seating is shared, so you will end up at a table with strangers. Arrive when doors open if you want a sightline.',
    ticketNote: 'Confirm whether the show is cash at the door or advance ticket before you go.',
    priceNote: '[Verify current pricing]',
    ageRestriction: '[Verify age policy]',
    parkingNote: 'Garage parking in the surrounding Gulch buildings. Street spots here are scarce after 6pm.',
    mapQuery: 'Station Inn, Nashville, TN',
    relatedSlugs: ['station-inn', 'sample-gulch-pasta-bar', 'sample-gulch-tower-hotel'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'event',
    slug: 'sample-ryman-fall-concert-night',
    title: '[Sample] Ryman Fall Concert Night',
    summary: 'A sample listing for a fall concert at the Ryman Auditorium.',
    startDate: '2026-10-02',
    timeNote: '[Verify current showtime]',
    venue: 'Ryman Auditorium',
    neighborhood: 'downtown-broadway',
    category: 'Concert',
    description:
      'A standard Ryman ticketed show. The building is a former tabernacle with wooden pews on two levels and a reputation for sound that carries without amplification. The pews have no backs on some rows.',
    ticketNote: 'Ticketed in advance. Popular shows sell out weeks ahead.',
    priceNote: '[Verify current pricing]',
    ageRestriction: '[Verify age policy]',
    parkingNote: 'Downtown garages within two blocks. Event-night rates apply, and the closest ones fill first.',
    mapQuery: 'Ryman Auditorium, Nashville, TN',
    relatedSlugs: ['ryman-auditorium', 'sample-broadway-high-rise-hotel', 'sample-broadway-barbecue-hall'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    dateUpdated: '2026-08-01',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'event',
    slug: 'sample-ascend-riverfront-show',
    title: '[Sample] Ascend Riverfront Show',
    summary: 'A sample listing for an outdoor concert at Ascend Amphitheater.',
    startDate: '2026-08-09',
    timeNote: '[Verify current showtime]',
    venue: 'Ascend Amphitheater',
    neighborhood: 'downtown-broadway',
    category: 'Concert',
    description:
      'An outdoor show on the riverfront with fixed seats down front and a lawn behind them. Lawn tickets cost less and the sightlines are fine, but August evenings here stay warm and humid well past sundown.',
    ticketNote: 'Ticketed in advance. Lawn tickets usually stay available longest.',
    priceNote: '[Verify current pricing]',
    ageRestriction: '[Verify age policy]',
    parkingNote: 'Use a downtown garage and walk. The lots closest to the riverfront clear slowly after the encore.',
    mapQuery: 'Ascend Amphitheater, Nashville, TN',
    relatedSlugs: ['ascend-amphitheater', 'sample-broadway-high-rise-hotel', 'country-music-hall-of-fame'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'event',
    slug: 'sample-bridgestone-hockey-night',
    title: '[Sample] Bridgestone Hockey Night',
    summary: 'A sample listing for a home hockey game at Bridgestone Arena.',
    startDate: '2026-10-17',
    timeNote: '[Verify current puck drop]',
    venue: 'Bridgestone Arena',
    neighborhood: 'downtown-broadway',
    category: 'Sports',
    description:
      'The arena sits at the top of Lower Broadway, so a game night pushes crowds straight onto the strip afterward. Upper-level seats are the value here and the sightlines stay good.',
    ticketNote: 'Ticketed in advance. Resale prices swing hard depending on the opponent.',
    priceNote: '[Verify current pricing]',
    ageRestriction: 'All ages. Every attendee needs a ticket.',
    parkingNote: 'Garages fill by an hour before puck drop and rates roughly double. Walking from a hotel is easier.',
    mapQuery: 'Bridgestone Arena, Nashville, TN',
    relatedSlugs: ['bridgestone-arena', 'sample-broadway-barbecue-hall', 'sample-broadway-high-rise-hotel'],
    dataStatus: 'unverified',
    dateChecked: '2026-07-28',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'event',
    slug: 'sample-weho-art-crawl',
    title: '[Sample] Wedgewood-Houston Art Crawl',
    summary: 'A sample listing for a monthly evening gallery crawl in the arts district.',
    startDate: '2026-08-08',
    timeNote: '[Verify current hours]',
    venue: 'Wedgewood-Houston galleries',
    neighborhood: 'wedgewood-houston',
    category: 'Free',
    description:
      'Galleries and studios open their doors on the same evening and you walk between them. Free to attend. Wear shoes you can cover a mile in, because the buildings are spread across several blocks.',
    ticketNote: 'No ticket. Walk up to any participating space.',
    priceNote: 'Free to attend. Confirm before you go.',
    ageRestriction: 'All ages, though the crowd skews adult after 8pm.',
    parkingNote: 'Free street and lot parking, but it goes fast on crawl nights. Park once and walk the whole route.',
    mapQuery: 'Wedgewood-Houston, Nashville, TN',
    relatedSlugs: ['sample-weho-gallery-walk', 'sample-weho-taqueria', 'sample-weho-warehouse-hotel'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'event',
    slug: 'sample-germantown-market-day',
    title: '[Sample] Germantown Market Day',
    summary: 'A sample listing for a weekend producer market at the Nashville Farmers\' Market.',
    startDate: '2026-08-22',
    endDate: '2026-08-23',
    timeNote: '[Verify current hours]',
    venue: 'Nashville Farmers\' Market',
    neighborhood: 'germantown',
    category: 'Food & Drink',
    description:
      'Open-air produce sheds next to an indoor food hall. Go in the morning while the sheds are still stocked and the food hall lines are short. Bring cash for the smaller stands.',
    ticketNote: 'No ticket needed to browse.',
    priceNote: 'Free entry. Vendor pricing varies.',
    ageRestriction: 'All ages.',
    parkingNote: 'Free on-site lot that fills by mid-morning on Saturdays.',
    mapQuery: "Nashville Farmers' Market, Nashville, TN",
    relatedSlugs: ['nashville-farmers-market', 'sample-germantown-chophouse', 'sample-germantown-boutique-hotel'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'event',
    slug: 'sample-shelby-bottoms-family-walk',
    title: '[Sample] Shelby Bottoms Family Walk',
    summary: 'A sample listing for a guided morning walk on the Shelby Bottoms greenway.',
    startDate: '2026-10-03',
    timeNote: '[Verify current start time]',
    venue: 'Shelby Bottoms Greenway',
    neighborhood: 'east-nashville',
    category: 'Family',
    description:
      'A flat, paved walk along the river with a guide pointing out birds and river ecology. Strollers handle the surface fine. October mornings start cool, so bring a layer you can take off.',
    ticketNote: 'Registration may be required. Check before you drive out.',
    priceNote: 'Free or low cost. Confirm before you go.',
    ageRestriction: 'All ages.',
    parkingNote: 'Free lot at the nature center trailhead. It fills on clear weekend mornings.',
    mapQuery: 'Shelby Bottoms Greenway, Nashville, TN',
    relatedSlugs: ['shelby-bottoms-greenway', 'sample-east-nashville-inn', 'sample-east-side-fish-counter'],
    dataStatus: 'unverified',
    dateChecked: '2026-07-28',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'event',
    slug: 'sample-east-nashville-block-party',
    title: '[Sample] East Nashville Block Party',
    summary: 'A sample listing for a neighborhood street festival in East Nashville.',
    startDate: '2026-08-29',
    endDate: '2026-08-30',
    timeNote: '[Verify current hours]',
    venue: 'Five Points, East Nashville',
    neighborhood: 'east-nashville',
    category: 'Festival',
    description:
      'Streets close, local bands play on a small stage, and restaurants run food outside. It is a local crowd more than a tourist one. Late August heat is the main complaint every year.',
    ticketNote: 'Free entry. Some food and drink require wristbands.',
    priceNote: 'Free to attend. Food and drink cost extra.',
    ageRestriction: 'All ages until early evening.',
    parkingNote: 'Street parking several blocks out, then walk. Road closures start in the morning.',
    mapQuery: 'Five Points, East Nashville, TN',
    relatedSlugs: ['sample-east-side-fish-counter', 'sample-east-nashville-listening-room', 'sample-east-nashville-inn'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    dateUpdated: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
];

/* ------------------------------------ Venues ------------------------------------- */

export const venues: Venue[] = [
  {
    kind: 'venue',
    slug: 'ryman-auditorium',
    title: 'Ryman Auditorium',
    summary: 'The former tabernacle downtown that housed the Grand Ole Opry for decades and still books nightly shows.',
    whyWeRecommend:
      'The best-sounding room in Nashville and the one show worth planning a trip around. The seating is wooden pews, so a three-hour bill gets uncomfortable if you have a bad back.',
    neighborhood: 'downtown-broadway',
    capacityNote: 'Mid-size seated hall on two levels. Every seat faces the stage. [Verify current capacity]',
    genres: ['Country', 'Americana', 'Bluegrass', 'Rock', 'Comedy'],
    coverNote: 'Ticketed shows only. No walk-up cover. [Verify current pricing]',
    address: '[Address — verify]',
    mapQuery: 'Ryman Auditorium, Nashville, TN',
    relatedSlugs: ['sample-ryman-fall-concert-night', 'country-music-hall-of-fame', 'sample-broadway-high-rise-hotel'],
    dataStatus: 'needs-recheck',
    dateChecked: '2026-07-28',
    dateUpdated: '2026-08-01',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'venue',
    slug: 'station-inn',
    title: 'Station Inn',
    summary: 'A small bluegrass room in the Gulch, surrounded on all sides by newer construction.',
    whyWeRecommend:
      'The bluegrass room people mean when they say Nashville still has real ones. Shared tables, a plain bar, and players who treat the room seriously. Get there early because seating is first come.',
    neighborhood: 'the-gulch',
    capacityNote: 'Small room, shared tables, standing room at the back. [Verify current capacity]',
    genres: ['Bluegrass', 'Country', 'Americana'],
    coverNote: 'Cover varies by night, and some shows sell in advance. [Verify current pricing]',
    address: '[Address — verify]',
    mapQuery: 'Station Inn, Nashville, TN',
    relatedSlugs: ['sample-fall-songwriter-round', 'sample-gulch-pasta-bar', 'sample-gulch-tower-hotel'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'venue',
    slug: 'bluebird-cafe',
    title: 'Bluebird Cafe',
    summary: 'A very small Green Hills room where songwriters perform in the round in a strip mall storefront.',
    whyWeRecommend:
      'Go for the writing rather than the performance. The room enforces quiet during songs, which is the whole point. Seats are few and go fast, so this only works if you plan weeks out.',
    neighborhood: 'green-hills',
    capacityNote: 'Very small. Roughly the size of a large living room. [Verify current capacity]',
    genres: ['Songwriter', 'Country', 'Folk'],
    coverNote: 'Reserved seats and a minimum spend are typical. [Verify current pricing]',
    address: '[Address — verify]',
    mapQuery: 'Bluebird Cafe, Nashville, TN',
    relatedSlugs: ['sample-green-hills-sushi-counter', 'sample-green-hills-suites', 'station-inn'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'venue',
    slug: 'ascend-amphitheater',
    title: 'Ascend Amphitheater',
    summary: 'An outdoor amphitheater on the downtown riverfront with fixed seating and a lawn.',
    whyWeRecommend:
      'The summer and fall touring room, with the skyline behind the stage. Lawn tickets are the value. Heat and afternoon storms are the risk from June through September.',
    neighborhood: 'downtown-broadway',
    capacityNote: 'Large outdoor venue with reserved seats plus a general admission lawn. [Verify current capacity]',
    genres: ['Rock', 'Country', 'Pop', 'Hip-hop'],
    coverNote: 'Ticketed shows only. [Verify current pricing]',
    address: '[Address — verify]',
    mapQuery: 'Ascend Amphitheater, Nashville, TN',
    relatedSlugs: ['sample-ascend-riverfront-show', 'sample-broadway-high-rise-hotel', 'bridgestone-arena'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'venue',
    slug: 'bridgestone-arena',
    title: 'Bridgestone Arena',
    summary: 'The downtown arena at the head of Lower Broadway, used for hockey and large concerts.',
    whyWeRecommend:
      'The only room downtown built for arena-scale shows, and it sits close enough to walk from most central hotels. Sound quality varies a lot depending on the production.',
    neighborhood: 'downtown-broadway',
    capacityNote: 'Large arena with lower bowl, club, and upper levels. [Verify current capacity]',
    genres: ['Arena rock', 'Country', 'Pop', 'Hockey'],
    coverNote: 'Ticketed events only. [Verify current pricing]',
    address: '[Address — verify]',
    mapQuery: 'Bridgestone Arena, Nashville, TN',
    relatedSlugs: ['sample-bridgestone-hockey-night', 'sample-broadway-barbecue-hall', 'ascend-amphitheater'],
    dataStatus: 'unverified',
    dateChecked: '2026-07-28',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'venue',
    slug: 'sample-east-nashville-listening-room',
    title: '[Sample] East Nashville Listening Room',
    summary: 'A sample record for a small listening room across the river from downtown.',
    whyWeRecommend:
      'Represents the neighborhood rooms where touring acts play on off nights. Low cover, early sets, and a crowd that mostly lives nearby. Sightlines suffer if you arrive after the opener.',
    neighborhood: 'east-nashville',
    capacityNote: 'Small standing room with limited seating along the walls.',
    genres: ['Indie', 'Americana', 'Soul', 'Songwriter'],
    coverNote: 'Low cover at the door on most nights.',
    address: '[Address — verify]',
    mapQuery: 'East Nashville, Nashville, TN',
    relatedSlugs: ['sample-east-nashville-block-party', 'sample-east-side-fish-counter', 'sample-east-nashville-inn'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
];

/* ---------------------------------- Attractions ---------------------------------- */

export const attractions: Attraction[] = [
  {
    kind: 'attraction',
    slug: 'country-music-hall-of-fame',
    title: 'Country Music Hall of Fame and Museum',
    summary: 'The main country music museum, sitting downtown a few blocks off Lower Broadway.',
    whyWeRecommend:
      'The single best use of an indoor afternoon downtown, especially if you read exhibit text. Rushing it in an hour wastes the ticket, so give it at least two.',
    neighborhood: 'downtown-broadway',
    category: 'Museum',
    priceNote: '[Verify current pricing]',
    timeNeeded: '2 to 3 hours. Longer if you add the studio tour.',
    bestFor: ['First-time visitors', 'Rainy days', 'Music history'],
    address: '[Address — verify]',
    mapQuery: 'Country Music Hall of Fame, Nashville, TN',
    indoor: true,
    familyFriendly: true,
    relatedSlugs: ['ryman-auditorium', 'sample-broadway-high-rise-hotel', 'sample-broadway-barbecue-hall'],
    dataStatus: 'unverified',
    dateChecked: '2026-07-28',
    dateUpdated: '2026-08-01',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'attraction',
    slug: 'the-parthenon',
    title: 'The Parthenon',
    summary: 'A full-scale replica of the Athenian Parthenon standing in Centennial Park.',
    whyWeRecommend:
      'Worth an hour, mostly for the scale of the building and the park around it. The exterior and the lawn are free, and that is enough for many visitors.',
    neighborhood: 'midtown',
    category: 'Landmark',
    priceNote: '[Verify current pricing]',
    timeNeeded: '45 minutes to 90 minutes with the park.',
    bestFor: ['Families', 'Photos', 'Short visits'],
    address: '[Address — verify]',
    mapQuery: 'The Parthenon, Nashville, TN',
    indoor: true,
    familyFriendly: true,
    relatedSlugs: ['sample-midtown-hot-chicken-counter', 'sample-midtown-value-hotel', 'sample-hillsboro-village-diner'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'attraction',
    slug: 'nashville-farmers-market',
    title: "Nashville Farmers' Market",
    summary: 'An indoor food hall and open-air produce sheds next to the capitol grounds in Germantown.',
    whyWeRecommend:
      'A practical lunch stop with several counters under one roof, which helps when a group cannot agree. Go before 1pm. The energy drops off in the afternoon.',
    neighborhood: 'germantown',
    category: 'Market',
    priceNote: 'Free to enter. Vendor pricing varies. [Verify current pricing]',
    timeNeeded: '1 to 2 hours including lunch.',
    bestFor: ['Lunch', 'Families', 'Groups of 6+'],
    address: '[Address — verify]',
    mapQuery: "Nashville Farmers' Market, Nashville, TN",
    indoor: true,
    familyFriendly: true,
    relatedSlugs: ['sample-germantown-market-day', 'sample-germantown-boutique-hotel', 'sample-germantown-chophouse'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'attraction',
    slug: 'shelby-bottoms-greenway',
    title: 'Shelby Bottoms Greenway',
    summary: 'A flat paved greenway along the Cumberland in East Nashville, with a nature center at one end.',
    whyWeRecommend:
      'The easiest outdoor hour in the city. Flat, shaded in stretches, and fine for strollers or a rented bike. There is little shade in the open sections, so go early in summer.',
    neighborhood: 'east-nashville',
    category: 'Park',
    priceNote: 'Free.',
    timeNeeded: '1 to 2 hours depending on how far you walk.',
    bestFor: ['Families', 'Running and walking', 'Morning outings'],
    address: '[Address — verify]',
    mapQuery: 'Shelby Bottoms Greenway, Nashville, TN',
    indoor: false,
    familyFriendly: true,
    relatedSlugs: ['sample-shelby-bottoms-family-walk', 'sample-east-nashville-inn', 'sample-east-side-fish-counter'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: INSTITUTION_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'attraction',
    slug: 'sample-weho-gallery-walk',
    title: '[Sample] Wedgewood-Houston Gallery Walk',
    summary: 'A sample self-guided route through the gallery buildings in the arts district.',
    whyWeRecommend:
      'A good alternative to Broadway for an afternoon. Most galleries here keep limited hours, often Thursday through Saturday, so check before you build a day around it.',
    neighborhood: 'wedgewood-houston',
    category: 'Art',
    priceNote: 'Most galleries are free to enter.',
    timeNeeded: '2 hours to cover the main buildings.',
    bestFor: ['Art', 'Avoiding crowds', 'Repeat visitors'],
    address: '[Address — verify]',
    mapQuery: 'Wedgewood-Houston, Nashville, TN',
    indoor: true,
    familyFriendly: false,
    relatedSlugs: ['sample-weho-art-crawl', 'sample-weho-taqueria', 'sample-weho-warehouse-hotel'],
    dataStatus: 'unverified',
    dateChecked: '2026-07-28',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'attraction',
    slug: 'sample-12-south-walking-loop',
    title: '[Sample] 12 South Walking Loop',
    summary: 'A sample walking route covering the 12 South commercial strip and the park at its south end.',
    whyWeRecommend:
      'The most efficient way to see 12 South, because the whole strip is under a mile end to end. Park once at the north end and walk. Weekend crowds slow the shopping considerably.',
    neighborhood: '12-south',
    category: 'Walking route',
    priceNote: 'Free.',
    timeNeeded: '90 minutes with coffee and a few shops.',
    bestFor: ['Couples', 'Shopping', 'Walkable afternoons'],
    address: '[Address — verify]',
    mapQuery: '12 South, Nashville, TN',
    indoor: false,
    familyFriendly: true,
    relatedSlugs: ['sample-12-south-brunch-room', 'sample-12-south-guesthouse', 'sample-green-hills-sushi-counter'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'attraction',
    slug: 'sample-sylvan-park-greenway-loop',
    title: '[Sample] Sylvan Park Greenway Loop',
    summary: 'A sample record for a short greenway loop through a residential west-side neighborhood.',
    whyWeRecommend:
      'For a visitor who runs in the morning and does not want a tourist route. Flat, shaded, and quiet. You need a car to get here.',
    neighborhood: 'sylvan-park',
    category: 'Park',
    priceNote: 'Free.',
    timeNeeded: '45 minutes to an hour.',
    bestFor: ['Running and walking', 'Solo travelers', 'Morning outings'],
    address: '[Address — verify]',
    mapQuery: 'Sylvan Park, Nashville, TN',
    indoor: false,
    familyFriendly: true,
    relatedSlugs: ['sample-sylvan-park-meat-and-three', 'the-parthenon'],
    dataStatus: 'unverified',
    dateChecked: '2026-08-01',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
  {
    kind: 'attraction',
    slug: 'sample-hillsboro-village-cinema',
    title: '[Sample] Hillsboro Village Cinema',
    summary: 'A sample record for an independent movie theater on the Hillsboro Village strip.',
    whyWeRecommend:
      'A useful rainy-afternoon option between two universities, and a break from music. Screens in this format are small and the seats are old, which some people like and some do not.',
    neighborhood: 'hillsboro-village',
    category: 'Cinema',
    priceNote: '[Verify current pricing]',
    timeNeeded: '2 to 3 hours with a show.',
    bestFor: ['Rainy days', 'Couples', 'Solo travelers'],
    address: '[Address — verify]',
    mapQuery: 'Hillsboro Village, Nashville, TN',
    indoor: true,
    familyFriendly: true,
    relatedSlugs: ['sample-hillsboro-village-diner', 'sample-midtown-value-hotel', 'the-parthenon'],
    dataStatus: 'unverified',
    dateChecked: '2026-07-28',
    sourceNote: DEMO_SOURCE_NOTE,
    placement: 'editorial',
  },
];

/* ---------------------------------- Lookup helpers -------------------------------- */

export function getRestaurant(slug: string): Restaurant | undefined {
  return restaurants.find((r) => r.slug === slug);
}

export function getHotel(slug: string): Hotel | undefined {
  return hotels.find((h) => h.slug === slug);
}

export function getEvent(slug: string): NashvilleEvent | undefined {
  return events.find((e) => e.slug === slug);
}

export function getVenue(slug: string): Venue | undefined {
  return venues.find((v) => v.slug === slug);
}

export function getAttraction(slug: string): Attraction | undefined {
  return attractions.find((a) => a.slug === slug);
}

export const allListings: Listing[] = [
  ...restaurants,
  ...hotels,
  ...events,
  ...venues,
  ...attractions,
];
