import type { Neighborhood } from '../types';

/**
 * Neighborhood orientation. Geography, character, and getting-around notes are
 * general local knowledge rather than claims about specific businesses.
 * Parking and transit specifics still carry a check date.
 */
export const neighborhoods: Neighborhood[] = [
  {
    slug: 'downtown-broadway',
    name: 'Downtown / Broadway',
    summary:
      'Lower Broadway and the blocks around it: free live music from late morning on, big hotels within walking distance, and the museums and arena stacked on the south edge.',
    overview: [
      'Lower Broadway is a short, dense strip of multi-floor bars with bands running most of the day and night. Entry is free; you pay for drinks. On Friday and Saturday nights the sidewalks fill early, and rideshares stack up at the ends of each block.',
      'Just off the strip you get the quieter pieces: the Ryman, the Country Music Hall of Fame, Bridgestone Arena, and the Pedestrian Bridge over the Cumberland. Those are the stops that make a downtown day feel like more than a bar crawl.',
      'Stay here if walking to nightlife matters more than sleep. Rooms facing Broadway will hear the street until close. If you want the same walkability with quieter nights, look at Germantown or the Gulch — both are a short walk or quick ride away.',
      'Tradeoffs are real: garage parking gets expensive on event nights, restaurants on the strip itself are priced for visitors, and the same three blocks can feel repetitive after a day. Use Broadway as the hub, then leave it for dinner or a show.',
    ],
    bestFor: ['First-time visitors', 'Groups', 'Walking to nightlife', 'Short trips'],
    knownFor: ['Honky-tonks', 'Live music', 'Hotels', 'Museums'],
    gettingThere:
      'Roughly 15-25 minutes from BNA by car depending on traffic. Once you are downtown, plan to walk; moving the car between nearby stops rarely saves time.',
    parkingNote:
      'Garages are the practical option; street parking is scarce and enforced. Rates jump on Titans, Predators, and big concert nights — budget for that or leave the car at the hotel.',
    halfDayItinerary: [
      { time: 'Late morning', activity: 'Country Music Hall of Fame', note: 'Budget two hours if you read the exhibits.' },
      { time: 'Lunch', activity: 'Meat-and-three or barbecue nearby', note: 'Lines peak 12-1pm; a few blocks off Broadway is usually faster.' },
      { time: 'Afternoon', activity: 'Walk Lower Broadway and the Pedestrian Bridge', note: 'The bridge has the clearest skyline view in the city.' },
      { time: 'Evening', activity: 'Ryman show or a honky-tonk crawl', note: 'Check the Ryman calendar before you lock the night.' },
    ],
    mapQuery: 'Lower Broadway, Nashville, TN',
    avoidIf: ["Light sleepers on Broadway-facing rooms","Quiet dinner every night"],
    walkability: 'Excellent — strip, museums, and arena are on foot.',
    nightlifeLevel: 'Very high',
    noiseLevel: 'High after dark; louder on weekends and event nights.',
    broadwayMinutes: { walk: 0, drive: 0 },
    typicalHotelPrice: '$$$–$$$$',
    landmarks: ['Lower Broadway', 'Ryman Auditorium', 'Country Music Hall of Fame', 'Pedestrian Bridge'],
    dateChecked: '2026-08-01',
  },
  {
    slug: '12-south',
    name: '12 South',
    summary:
      'A walkable half-mile of restaurants, coffee, and boutiques through a pocket of bungalows south of downtown — easy to cover on foot once you park.',
    overview: [
      '12 South is a residential neighborhood with a commercial spine along 12th Avenue South. The stretch most visitors mean is only a few blocks: coffee, clothing, patio restaurants, and the “I Believe in Nashville” mural that draws a steady photo line.',
      'Weekends get busy. Popular brunch and coffee spots run waits after mid-morning, and street parking fills by late morning. Weekday mornings and late afternoons are calmer and better for browsing.',
      'It works well as a half-day base: park once, walk the strip, cut over to Sevier Park, then rideshare downtown (about ten minutes) for the evening. Staying overnight here means quieter nights than Broadway with a short hop to the center.',
      'Do not treat it as a full-trip neighborhood on its own — nightlife and major museums are elsewhere. Pair it with Hillsboro Village or Midtown if you want a full south-side day.',
    ],
    bestFor: ['Couples', 'Coffee and shopping', 'Walkable afternoons', 'Brunch'],
    knownFor: ['Boutiques', 'Coffee', 'Brunch', 'Murals'],
    gettingThere: 'About 10 minutes by car from downtown. Rideshare is simpler than fighting for street parking on weekends.',
    parkingNote:
      'Street parking only on most blocks, and it fills on weekends. Side streets are residential — watch signs and time limits.',
    halfDayItinerary: [
      { time: 'Morning', activity: 'Coffee on the strip', note: 'Arrive before 10am on weekends to skip the longest waits.' },
      { time: 'Late morning', activity: 'Browse boutiques and the mural', note: 'Most retail sits in a four-block stretch.' },
      { time: 'Lunch', activity: 'Patio lunch on 12th Ave S', note: 'Outdoor seating is the draw in spring and fall.' },
      { time: 'Afternoon', activity: 'Walk to Sevier Park', note: 'Shaded and quiet — a useful reset before dinner downtown.' },
    ],
    mapQuery: '12 South, Nashville, TN',
    avoidIf: ["Visitors who need nightlife outside the door","Anyone unwilling to rideshare downtown"],
    walkability: 'Excellent on the commercial strip; residential beyond.',
    nightlifeLevel: 'Moderate',
    noiseLevel: 'Low at night; weekend brunch crowds are the main friction.',
    broadwayMinutes: { drive: 10 },
    typicalHotelPrice: '$$–$$$',
    landmarks: ['12th Avenue South', 'I Believe in Nashville mural', 'Sevier Park'],
    dateChecked: '2026-08-01',
  },
  {
    slug: 'the-gulch',
    name: 'The Gulch',
    summary:
      'A compact, recently built district between downtown and Midtown — hotels, restaurants, and the Station Inn within a walkable grid.',
    overview: [
      'The Gulch sits in the old rail yards south of Broadway. What you see now is mid-rise residential, street-level restaurants, and hotels packed into a few walkable blocks. It is tidy, vertical, and easy to cover on foot in under an hour.',
      'People stay here to be near downtown without sleeping on Broadway. You can walk to Lower Broadway in about fifteen minutes, or rideshare in five. The Station Inn anchors a more traditional music night if you want bluegrass instead of a honky-tonk crawl.',
      'Prices run higher than East Nashville or Sylvan Park for both rooms and dinner. The trade is convenience: garage parking under buildings, sidewalks that feel lit and busy, and a concentration of newer hotels.',
      'It is not the place for quiet residential mornings or bargain eats. Come for a polished central base; leave for East Nashville or Germantown when you want a different dinner neighborhood.',
    ],
    bestFor: ['Groups', 'Hotel stays', 'Walkability', 'Nightlife without Broadway'],
    knownFor: ['Hotels', 'Restaurants', 'Bluegrass at the Station Inn', 'Murals'],
    gettingThere: 'Walking distance from downtown, roughly 15 minutes. About 15-20 minutes from BNA by car.',
    parkingNote: 'Garage parking under most buildings, usually paid. Validation varies by restaurant — ask when you book.',
    halfDayItinerary: [
      { time: 'Morning', activity: 'Coffee and a loop through the district', note: 'Compact enough to cover in 30 minutes.' },
      { time: 'Lunch', activity: 'Sit-down lunch in the Gulch', note: 'Reservations help on weekends.' },
      { time: 'Afternoon', activity: 'Walk toward downtown via Demonbreun', note: 'About 15 minutes on foot to Broadway.' },
      { time: 'Evening', activity: 'Bluegrass at the Station Inn', note: 'Small room; arrive early for a seat. Cash bar.' },
    ],
    mapQuery: 'The Gulch, Nashville, TN',
    avoidIf: ["Budget hotel hunters","Visitors who want a residential neighborhood feel"],
    walkability: 'Excellent within the district; about 15 minutes on foot to Broadway.',
    nightlifeLevel: 'High',
    noiseLevel: 'Moderate to high on Demonbreun; quieter than Broadway rooms.',
    broadwayMinutes: { walk: 15, drive: 5 },
    typicalHotelPrice: '$$$–$$$$',
    landmarks: ['Station Inn', 'Demonbreun Street', 'Gulch greenway'],
    dateChecked: '2026-08-01',
  },
  {
    slug: 'east-nashville',
    name: 'East Nashville',
    summary:
      'Across the Cumberland from downtown: independent restaurants, bars, and shops spread across Five Points, Riverside, and other walkable pockets.',
    overview: [
      'East Nashville is not one strip. Five Points, the Riverside Village area, and smaller clusters along Main and Gallatin each have their own restaurants and bars. Plan on driving or ridesharing between pockets rather than walking the whole neighborhood.',
      'This is where a lot of locals send visitors for dinner when Broadway feels too loud. Rooms are smaller, menus change, and the crowd skews less tourist-heavy — especially on weeknights. Brunch waits on Saturdays are still real.',
      'Shelby Bottoms Greenway and the river parks give you an easy outdoor break without leaving the east side. Downtown is five to ten minutes by car across the bridge; walking from downtown is not practical.',
      'Stay here if food and a neighborhood feel matter more than museum walking distance. You will need a car or steady rideshare budget.',
    ],
    bestFor: ['Food-focused trips', 'Repeat visitors', 'Bars', 'Brunch'],
    knownFor: ['Independent restaurants', 'Dive bars', 'Vintage shops', 'Live music'],
    gettingThere: 'About 5-10 minutes by car from downtown across the Cumberland. Budget rideshares into the evening.',
    parkingNote: 'Mostly free street parking; tighter around the busiest blocks on weekend nights. Do not block driveways on residential side streets.',
    halfDayItinerary: [
      { time: 'Morning', activity: 'Brunch in the Five Points area', note: 'Expect a wait after 10am on weekends.' },
      { time: 'Late morning', activity: 'Vintage and record shopping', note: 'Several shops within a few blocks of each other.' },
      { time: 'Afternoon', activity: 'Shelby Bottoms Greenway', note: 'Flat, shaded walking and biking along the river.' },
      { time: 'Evening', activity: 'Dinner and a neighborhood bar', note: 'Smaller rooms; book dinner ahead on weekends.' },
    ],
    mapQuery: 'East Nashville, Nashville, TN',
    avoidIf: ["First-timers who want to walk to the Ryman","Visitors without a rideshare budget"],
    walkability: 'Good inside pockets (Five Points); poor across the whole east side.',
    nightlifeLevel: 'High',
    noiseLevel: 'Moderate — busier near bars on weekend nights.',
    broadwayMinutes: { drive: 8 },
    typicalHotelPrice: '$$–$$$',
    landmarks: ['Five Points', 'Shelby Bottoms Greenway', 'Main Street'],
    dateChecked: '2026-08-01',
  },
  {
    slug: 'germantown',
    name: 'Germantown',
    summary:
      'A compact historic district north of downtown: brick streets, a dense restaurant row, and an easy walk to the Farmers’ Market and capitol grounds.',
    overview: [
      'Germantown is small — most of the dining and wandering fits in about six blocks of late-1800s brick housing and newer infill. It feels settled and quiet compared with Broadway, which is roughly a twenty-minute walk south.',
      'Dinner is the neighborhood’s strength. Reservations matter on weekends. Mornings work well for the Nashville Farmers’ Market and Bicentennial Capitol Mall State Park next door, both useful when you want something free and outdoors without leaving the center of town.',
      'Game nights at the ballpark tighten parking and add crowd noise on the edges. Otherwise it is one of the better places to sleep near downtown if you want calm after dinner.',
      'Pair Germantown with a downtown morning of museums, then come back north for the evening. It is a weak base only if you need Broadway nightlife outside your door.',
    ],
    bestFor: ['Dinner', 'Couples', 'Quieter downtown-adjacent stays', 'Walking'],
    knownFor: ['Restaurants', 'Historic architecture', 'Farmers market', 'Baseball'],
    gettingThere: 'About 20 minutes on foot from downtown, or 5 minutes by car. Easy rideshare to Broadway.',
    parkingNote: 'Street parking plus a few small lots. Fills on Sounds game nights and busy restaurant weekends.',
    halfDayItinerary: [
      { time: 'Morning', activity: 'Nashville Farmers’ Market', note: 'Food hall plus produce sheds; good casual lunch option too.' },
      { time: 'Late morning', activity: 'Walk the historic blocks', note: 'Late 1800s brick housing stock; compact and photogenic.' },
      { time: 'Afternoon', activity: 'Bicentennial Capitol Mall State Park', note: 'Free, open, and a clear overview of state history.' },
      { time: 'Evening', activity: 'Dinner in Germantown', note: 'Reserve ahead — this is the neighborhood’s main draw.' },
    ],
    mapQuery: 'Germantown, Nashville, TN',
    avoidIf: ["People who want Broadway outside the lobby","Game-night light sleepers near the ballpark"],
    walkability: 'Excellent inside the district; about 20 minutes on foot to downtown.',
    nightlifeLevel: 'Moderate',
    noiseLevel: 'Low most nights; louder on Sounds game evenings.',
    broadwayMinutes: { walk: 20, drive: 5 },
    typicalHotelPrice: '$$$–$$$$',
    landmarks: ['Nashville Farmers Market', 'Bicentennial Capitol Mall', 'Historic brick streets'],
    dateChecked: '2026-08-01',
  },
  {
    slug: 'wedgewood-houston',
    name: 'Wedgewood-Houston',
    summary:
      'A former industrial pocket south of downtown — galleries, studios, and breweries in warehouse buildings, with Melrose and Berry Hill next door.',
    overview: [
      'Wedgewood-Houston (WeHo) grew out of warehouse and light-industrial blocks between downtown and the fairgrounds. Galleries and studios still set the tone; breweries and restaurants fill in around them. It feels less polished than the Gulch and far less crowded than Broadway.',
      'The monthly art crawls are when the neighborhood is most awake. Other days, check gallery hours before you go — many open Thursday through Saturday rather than seven days a week. Melrose and Berry Hill sit immediately alongside and add more food and nightlife options without a long drive.',
      'Come for an afternoon of galleries and a taproom, or an evening that avoids the downtown crush. It is a weak choice as a first-time visitor’s only base: you will still rideshare for museums, Broadway, and most hotels.',
      'About ten minutes from downtown by car. Free-ish parking most days; crawls and weekend nights are the exception.',
    ],
    bestFor: ['Art', 'Breweries', 'Avoiding crowds', 'Repeat visitors'],
    knownFor: ['Galleries', 'Breweries', 'Art crawls', 'Studios'],
    gettingThere: 'Roughly 10 minutes by car from downtown. Not a pleasant walk from Broadway.',
    parkingNote: 'Free street and lot parking most days. Art crawl nights fill fast — arrive early or use rideshare.',
    halfDayItinerary: [
      { time: 'Afternoon', activity: 'Gallery walk', note: 'Confirm hours; many spaces open Thursday to Saturday.' },
      { time: 'Late afternoon', activity: 'Brewery taproom', note: 'Several within walking distance of each other.' },
      { time: 'Evening', activity: 'Dinner in WeHo, Melrose, or Berry Hill', note: 'Smaller scene than Germantown; usually easier tables.' },
    ],
    mapQuery: 'Wedgewood-Houston, Nashville, TN',
    avoidIf: ["First-timers who want a single walkable base","Visitors expecting dense hotel inventory"],
    walkability: 'Fair — galleries cluster; still plan on a car or rideshare.',
    nightlifeLevel: 'Moderate',
    noiseLevel: 'Low to moderate; busiest on art crawl nights.',
    broadwayMinutes: { drive: 10 },
    typicalHotelPrice: '$$–$$$',
    landmarks: ['Gallery row', 'Brewery taprooms', 'Melrose / Berry Hill edge'],
    dateChecked: '2026-08-01',
  },
  {
    slug: 'midtown',
    name: 'Midtown',
    summary:
      'West of downtown along Broadway and West End: Music Row, Vanderbilt’s edge, Centennial Park, and a younger bar scene.',
    overview: [
      'Midtown covers a lot of ground: Music Row’s publishing houses and studios in converted homes, the student-heavy blocks near Vanderbilt, and Centennial Park with the Parthenon on West End. It is less of a single strip than a band of neighborhoods between downtown and the west side.',
      'Hot chicken counters and Division / Demonbreun bars pull evening traffic. Music Row itself is mostly working offices — worth a walk for context, not a full afternoon of attractions. RCA Studio B is the ticketed exception, booked through the Country Music Hall of Fame.',
      'Hotel rates often undercut downtown for a similar drive time. You will still want a car or rideshare for East Nashville, 12 South, and many dinners. Vanderbilt event nights tighten parking and traffic on West End.',
      'Good base if you want Music Row history, park time, and nightlife that is not Broadway — and you do not mind hopping for everything else.',
    ],
    bestFor: ['Music industry history', 'Hot chicken', 'Younger nightlife', 'Value stays'],
    knownFor: ['Music Row', 'Hot chicken', 'Vanderbilt', 'Centennial Park'],
    gettingThere: 'About 5-10 minutes by car from downtown; walkable in around 25 minutes along Broadway / West End.',
    parkingNote: 'Mixed street and garage parking. Vanderbilt and Centennial Park event days tighten it considerably.',
    halfDayItinerary: [
      { time: 'Morning', activity: 'RCA Studio B tour', note: 'Ticketed through the Country Music Hall of Fame — book ahead.' },
      { time: 'Lunch', activity: 'Hot chicken', note: 'Order one heat level below what you think you want.' },
      { time: 'Afternoon', activity: 'Centennial Park and the Parthenon', note: 'Free grounds; museum inside the Parthenon is ticketed.' },
      { time: 'Evening', activity: 'Bars around Division and Demonbreun', note: 'Busiest Thursday through Saturday.' },
    ],
    mapQuery: 'Midtown, Nashville, TN',
    avoidIf: ["Visitors who want everything without rideshares","Quiet residential stays"],
    walkability: 'Good near Vanderbilt / Division; Music Row is more drive-and-park.',
    nightlifeLevel: 'High',
    noiseLevel: 'Moderate to high near Division and Demonbreun.',
    broadwayMinutes: { walk: 25, drive: 8 },
    typicalHotelPrice: '$$–$$$',
    landmarks: ['Music Row', 'Centennial Park / Parthenon', 'Vanderbilt edge'],
    dateChecked: '2026-08-01',
  },
  {
    slug: 'hillsboro-village',
    name: 'Hillsboro Village',
    summary:
      'Two walkable blocks of storefronts between Vanderbilt and Belmont — long-running restaurants, shops, and an independent theater.',
    overview: [
      'Hillsboro Village is a short commercial strip on 21st Avenue South with a settled, everyday feel. Several businesses have been here for decades, which makes it a useful counterweight to newer districts built in the last fifteen years.',
      'It is easy to combine with 12 South (a few minutes south) or Centennial Park (a longer walk or short ride north). Students from Vanderbilt and Belmont keep the sidewalks active during the school year without turning it into a nightlife strip.',
      'Come for coffee, a meal, a bookstore browse, or a film — not for a full day of attractions. Parking tightens when classes are in session.',
      'A strong add-on to a south Nashville day; a weak sole base if you need Broadway or the arena within walking distance.',
    ],
    bestFor: ['Coffee', 'Low-key afternoons', 'Students and academics', 'Independent film'],
    knownFor: ['Independent theater', 'Long-running restaurants', 'Bookshops', 'Coffee'],
    gettingThere: 'About 10 minutes by car from downtown. Easy to chain with 12 South by rideshare.',
    parkingNote: 'Street parking and a small garage. Tightest during Vanderbilt terms and weekend brunch hours.',
    halfDayItinerary: [
      { time: 'Morning', activity: 'Coffee and a bookshop', note: 'The strip is short; 30 minutes covers a first pass.' },
      { time: 'Lunch', activity: 'Lunch in the Village', note: 'Several long-running rooms; weekends fill up.' },
      { time: 'Afternoon', activity: 'Walk or ride to Centennial Park', note: 'Parthenon and open lawn; about 15 minutes by car or a longer walk.' },
    ],
    mapQuery: 'Hillsboro Village, Nashville, TN',
    avoidIf: ["Visitors who need a nightlife base","Anyone expecting a full day of attractions"],
    walkability: 'Excellent on the two-block strip.',
    nightlifeLevel: 'Low',
    noiseLevel: 'Low; student daytime foot traffic during terms.',
    broadwayMinutes: { drive: 10 },
    typicalHotelPrice: '$$–$$$',
    landmarks: ['21st Avenue South', 'Independent theater', 'Belmont / Vanderbilt edge'],
    dateChecked: '2026-08-01',
  },
  {
    slug: 'sylvan-park',
    name: 'Sylvan Park',
    summary:
      'A residential west-side neighborhood with a small restaurant row, Richland Creek Greenway access, and almost no tourist traffic.',
    overview: [
      'Sylvan Park is mostly houses. The visitor-facing piece is a compact commercial stretch along Murphy Road and 46th Avenue — independent restaurants and everyday shops rather than a programmed tourist strip.',
      'Richland Creek Greenway cuts through for flat walking and running. Centennial Park is a short drive east if you want the Parthenon after a neighborhood lunch. You will not end up here by accident, and that is the point for people who want a meal without a wait list.',
      'A car is effectively required. Downtown is about fifteen minutes depending on West End traffic. It is a strong longer-stay or locals’ recommendation; a weak first-night base if your itinerary is Broadway-heavy.',
      'Use it for a quiet lunch and a greenway walk when the center of town feels loud.',
    ],
    bestFor: ['Locals', 'Quiet meals', 'Running and walking', 'Longer stays'],
    knownFor: ['Neighborhood restaurants', 'Greenway', 'Residential streets', 'Parks'],
    gettingThere: 'Roughly 15 minutes by car from downtown. Plan on driving or rideshare both ways.',
    parkingNote: 'Free street parking, generally easy outside peak dinner hours.',
    halfDayItinerary: [
      { time: 'Morning', activity: 'Richland Creek Greenway', note: 'Flat and shaded; good before the day warms up.' },
      { time: 'Lunch', activity: 'Lunch on the 46th Ave / Murphy Rd strip', note: 'Small, mostly independent rooms; weekdays are calmest.' },
      { time: 'Afternoon', activity: 'Drive to Centennial Park', note: 'About 8 minutes east for the Parthenon and lawn.' },
    ],
    mapQuery: 'Sylvan Park, Nashville, TN',
    avoidIf: ["Car-free trips","First nights that depend on Broadway walking distance"],
    walkability: 'Good for greenway and the restaurant pocket; not a tourist grid.',
    nightlifeLevel: 'Low',
    noiseLevel: 'Low.',
    broadwayMinutes: { drive: 15 },
    typicalHotelPrice: '$$–$$$',
    landmarks: ['Richland Creek Greenway', 'Murphy Road / 46th Avenue'],
    dateChecked: '2026-08-01',
  },
  {
    slug: 'green-hills',
    name: 'Green Hills',
    summary:
      'An affluent south-side district for shopping and the Bluebird Cafe — residential streets around a busy Hillsboro Pike corridor.',
    overview: [
      'Green Hills is shopping and neighborhoods first: the mall and the Hillsboro Pike commercial strip, surrounded by established residential streets. It does not try to be downtown, and the drive in traffic can feel longer than the map suggests.',
      'The Bluebird Cafe is the visitor magnet — a small songwriter room that sells out in advance. Treat tickets as the reason for the trip south, then fill the afternoon with shopping or dinner nearby. Walk-up hopes are a poor plan.',
      'Families and quieter stays work well here. Nightlife and museums mean a ride back toward the center. Parking at the mall and larger lots is easier than downtown garages.',
      'Skip it on a short first visit unless you already hold Bluebird tickets or specifically want a shopping afternoon away from Broadway.',
    ],
    bestFor: ['Shopping', 'Songwriter shows', 'Quiet stays', 'Families'],
    knownFor: ['Bluebird Cafe', 'Shopping', 'Residential streets', 'Restaurants'],
    gettingThere: 'About 15-20 minutes by car from downtown; longer at rush hour on Hillsboro Pike.',
    parkingNote: 'Ample lot and garage parking at the mall and most plazas, most of it free.',
    halfDayItinerary: [
      { time: 'Afternoon', activity: 'Shopping on Hillsboro Pike', note: 'The mall anchors the district; boutiques fill the side plazas.' },
      { time: 'Early evening', activity: 'Dinner nearby', note: 'Reserve; the area gets busy around 6pm.' },
      { time: 'Evening', activity: 'Bluebird Cafe round', note: 'Reservations open in advance and go quickly. Plan ahead.' },
    ],
    mapQuery: 'Green Hills, Nashville, TN',
    avoidIf: ["Short first visits without Bluebird tickets","Visitors who hate Hillsboro Pike traffic"],
    walkability: 'Poor for sightseeing — plan on driving between stops.',
    nightlifeLevel: 'Low',
    noiseLevel: 'Low away from the Pike; traffic noise on the corridor.',
    broadwayMinutes: { drive: 18 },
    typicalHotelPrice: '$$$–$$$$',
    landmarks: ['Bluebird Cafe', 'Hillsboro Pike', 'The Mall at Green Hills'],
    dateChecked: '2026-08-01',
  },
];

export function getNeighborhood(slug: string): Neighborhood | undefined {
  return neighborhoods.find((n) => n.slug === slug);
}

export function neighborhoodName(slug: string): string {
  return getNeighborhood(slug)?.name ?? slug;
}
