/** Auto-generated by scripts/media/import-cvc.py from docs/media/cvc-intake/manifest.json. Do not edit by hand. */
import type { MediaAsset } from './media-types';

/** Visit Music City frames imported from the NCVC Brandfolder share; editorial placements only. */
export const cvcMedia = {
} as const satisfies Record<string, MediaAsset>;

export const CVC_IMPORTED_KEYS = Object.keys(cvcMedia) as Array<keyof typeof cvcMedia>;
