/** Auto-generated from docs/media/RESTORE-MANIFEST.json — do not edit by hand. */
import type { MediaAsset } from './media-types';

export const restoredMedia = {
  'attractions/cheekwood-estate-gardens': {
    src: '/media/attractions/cheekwood-estate-gardens.jpg',
    srcSet: '/media/attractions/cheekwood-estate-gardens-640.webp 640w, /media/attractions/cheekwood-estate-gardens-960.webp 960w, /media/attractions/cheekwood-estate-gardens-1600.webp 1600w, /media/attractions/cheekwood-estate-gardens-2400.webp 2400w',
    alt: 'Gardens and grounds at Cheekwood Estate & Gardens in Nashville.',
    credit: 'Sharon Mollerus',
    licence: 'CC BY 2.0 — https://commons.wikimedia.org/wiki/File%3ACheekwood_Estate_%26_Gardens%2C_Nashville_3_24_21_%2851118861080%29.jpg',
    width: 3143,
    height: 2514,
  },
  'attractions/country-music-hall-of-fame': {
    src: '/media/attractions/country-music-hall-of-fame.jpg',
    srcSet: '/media/attractions/country-music-hall-of-fame-640.webp 640w, /media/attractions/country-music-hall-of-fame-960.webp 960w, /media/attractions/country-music-hall-of-fame-1600.webp 1600w, /media/attractions/country-music-hall-of-fame-2400.webp 2400w',
    alt: 'Exterior of the Country Music Hall of Fame and Museum in downtown Nashville.',
    credit: 'Antony-22',
    licence: 'CC BY-SA 4.0 — https://commons.wikimedia.org/wiki/File%3ACountry_Music_Hall_of_Fame_2022c.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3199,
    height: 2133,
  },
  'attractions/frist-art-museum': {
    src: '/media/attractions/frist-art-museum.jpg',
    srcSet: '/media/attractions/frist-art-museum-640.webp 640w, /media/attractions/frist-art-museum-960.webp 960w, /media/attractions/frist-art-museum-1600.webp 1600w, /media/attractions/frist-art-museum-2400.webp 2400w',
    alt: 'The Frist Art Museum building at Broadway and Ninth Avenue in Nashville.',
    credit: 'Warren LeMay from Chicago, IL, United States',
    licence: 'CC BY-SA 2.0 — https://commons.wikimedia.org/wiki/File%3AOld_Nashville_Post_Office_%28Frist_Art_Museum%29%2C_Broadway_and_9th_Avenue%2C_Nashville%2C_TN_%2854384287651%29.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2399,
  },
  'attractions/nashville-farmers-market': {
    src: '/media/attractions/nashville-farmers-market.jpg',
    srcSet: '/media/attractions/nashville-farmers-market-640.webp 640w, /media/attractions/nashville-farmers-market-960.webp 960w, /media/attractions/nashville-farmers-market-1600.webp 1600w, /media/attractions/nashville-farmers-market-2400.webp 2400w',
    alt: 'Vendors and shoppers inside Nashville Farmers\' Market.',
    credit: 'Marty Bahamonde',
    licence: 'Public Domain — https://commons.wikimedia.org/wiki/File%3AFEMA_-_44075_-_Disaster_Officials_meet_with_food_vendors_in_Tennessee.jpg (Interim exact-location federal photo (2010); replace with owned shoot.; Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2125,
  },
  'attractions/nmaam': {
    src: '/media/attractions/nmaam.jpg',
    srcSet: '/media/attractions/nmaam-640.webp 640w, /media/attractions/nmaam-960.webp 960w, /media/attractions/nmaam-1600.webp 1600w, /media/attractions/nmaam-2400.webp 2400w',
    alt: 'National Museum of African American Music at Fifth + Broadway in Nashville.',
    credit: 'Warren LeMay from Chicago, IL, United States',
    licence: 'CC BY-SA 2.0 — https://commons.wikimedia.org/wiki/File%3ANational_Museum_of_African_American_Music%2C_Fifth_%2B_Broadway%2C_Broadway_and_5th_Avenue%2C_Nashville%2C_TN_%2854384524318%29.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 2400,
    height: 3200,
  },
  'attractions/ryman-auditorium-tour': {
    src: '/media/attractions/ryman-auditorium-tour.jpg',
    srcSet: '/media/attractions/ryman-auditorium-tour-640.webp 640w, /media/attractions/ryman-auditorium-tour-960.webp 960w, /media/attractions/ryman-auditorium-tour-1600.webp 1600w, /media/attractions/ryman-auditorium-tour-2400.webp 2400w',
    alt: 'Exterior of the Ryman Auditorium on Fifth Avenue in Nashville.',
    credit: 'Warren LeMay from Chicago, IL, United States',
    licence: 'CC BY-SA 2.0 — https://commons.wikimedia.org/wiki/File%3ARyman_Auditorium%2C_5th_Avenue%2C_Nashville%2C_TN_%2854384525798%29.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 2400,
    height: 3200,
  },
  'attractions/the-parthenon': {
    src: '/media/attractions/the-parthenon.jpg',
    srcSet: '/media/attractions/the-parthenon-640.webp 640w, /media/attractions/the-parthenon-960.webp 960w, /media/attractions/the-parthenon-1600.webp 1600w',
    alt: 'The Parthenon replica in Centennial Park, Nashville.',
    credit: 'Euthman',
    licence: 'CC BY 4.0 — https://commons.wikimedia.org/wiki/File%3AThe_Parthenon_replica%2C_Centennial_Park%2C_Nashville%2C_Tennessee.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 1243,
  },
  'guide/bars-rooftops': {
    src: '/media/guides/best-bars-rooftops-nashville.jpg',
    srcSet: '/media/guides/best-bars-rooftops-nashville-640.webp 640w, /media/guides/best-bars-rooftops-nashville-960.webp 960w, /media/guides/best-bars-rooftops-nashville-1600.webp 1600w, /media/guides/best-bars-rooftops-nashville-2400.webp 2400w',
    alt: 'Bars and rooftops beneath the Nashville skyline.',
    credit: 'Karakorhummel',
    licence: 'CC BY-SA 4.0 — https://commons.wikimedia.org/wiki/File%3ANashville_skyline_and_bars.jpg (Landscape crop preserving bar/rooftop context.; Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2133,
  },
  'guide/best-restaurants': {
    src: '/media/guides/best-restaurants-nashville.jpg',
    srcSet: '/media/guides/best-restaurants-nashville-640.webp 640w, /media/guides/best-restaurants-nashville-960.webp 960w, /media/guides/best-restaurants-nashville-1600.webp 1600w, /media/guides/best-restaurants-nashville-2400.webp 2400w',
    alt: 'Nashville-style hot chicken drumsticks served with pickles.',
    credit: 'Myspiritanimalisamanatee',
    licence: 'CC BY-SA 4.0 — https://commons.wikimedia.org/wiki/File%3ANashville_Hot_Chicken_Drumsticks.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2151,
  },
  'guide/first-time-visitors': {
    src: '/media/guides/nashville-first-time-visitors.jpg',
    srcSet: '/media/guides/nashville-first-time-visitors-640.webp 640w, /media/guides/nashville-first-time-visitors-960.webp 960w, /media/guides/nashville-first-time-visitors-1600.webp 1600w, /media/guides/nashville-first-time-visitors-2400.webp 2400w',
    alt: 'Lower Broadway at Fourth Avenue in downtown Nashville.',
    credit: 'Warren LeMay from Chicago, IL, United States',
    licence: 'CC BY-SA 2.0 — https://commons.wikimedia.org/wiki/File%3ABroadway_and_4th_Avenue%2C_Nashville%2C_TN_%2854384489114%29.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2400,
  },
  'guide/live-music-venues': {
    src: '/media/guides/best-live-music-venues-nashville.jpg',
    srcSet: '/media/guides/best-live-music-venues-nashville-640.webp 640w, /media/guides/best-live-music-venues-nashville-960.webp 960w, /media/guides/best-live-music-venues-nashville-1600.webp 1600w, /media/guides/best-live-music-venues-nashville-2400.webp 2400w',
    alt: 'A large live performance at Ascend Amphitheater in downtown Nashville.',
    credit: 'U.S. Marine Corps photo by Cpl. Vincent Needham',
    licence: 'Public Domain — https://commons.wikimedia.org/wiki/File%3AMarine_Week_Nashville%3B_2nd_MAW_band_at_CMA_fest_%289103794%29.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2133,
  },
  'guide/neighborhood-guide': {
    src: '/media/guides/nashville-neighborhood-guide.jpg',
    srcSet: '/media/guides/nashville-neighborhood-guide-640.webp 640w, /media/guides/nashville-neighborhood-guide-960.webp 960w, /media/guides/nashville-neighborhood-guide-1600.webp 1600w, /media/guides/nashville-neighborhood-guide-2400.webp 2400w',
    alt: 'Downtown Nashville skyline over the Cumberland River.',
    credit: 'Quintin Soloviev',
    licence: 'CC BY 4.0 — https://commons.wikimedia.org/wiki/File%3ANashville%2C_TN_skyline.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 1999,
  },
  'hub/neighborhoods-index': {
    src: '/media/hubs/neighborhoods-index.jpg',
    srcSet: '/media/hubs/neighborhoods-index-640.webp 640w, /media/hubs/neighborhoods-index-960.webp 960w, /media/hubs/neighborhoods-index-1600.webp 1600w, /media/hubs/neighborhoods-index-2400.webp 2400w',
    alt: 'Downtown Nashville skyline over the Cumberland River.',
    credit: 'Quintin Soloviev',
    licence: 'CC BY 4.0 — https://commons.wikimedia.org/wiki/File%3ANashville%2C_TN_skyline.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 1999,
  },
  'music/ascend-amphitheater': {
    src: '/media/music/ascend-amphitheater.jpg',
    srcSet: '/media/music/ascend-amphitheater-640.webp 640w, /media/music/ascend-amphitheater-960.webp 960w, /media/music/ascend-amphitheater-1600.webp 1600w, /media/music/ascend-amphitheater-2400.webp 2400w',
    alt: 'A large live performance at Ascend Amphitheater in downtown Nashville.',
    credit: 'U.S. Marine Corps photo by Cpl. Vincent Needham',
    licence: 'Public Domain — https://commons.wikimedia.org/wiki/File%3AMarine_Week_Nashville%3B_2nd_MAW_band_at_CMA_fest_%289103794%29.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2133,
  },
  'music/bluebird-cafe': {
    src: '/media/music/bluebird-cafe.jpg',
    srcSet: '/media/music/bluebird-cafe-640.webp 640w, /media/music/bluebird-cafe-960.webp 960w, /media/music/bluebird-cafe-1600.webp 1600w, /media/music/bluebird-cafe-2400.webp 2400w',
    alt: 'A live performance inside The Bluebird Cafe in Nashville.',
    credit: 'Purple7Management',
    licence: 'CC BY-SA 3.0 — https://commons.wikimedia.org/wiki/File%3AJillian_Kohr_Live_At_The_Bluebird_Cafe.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2179,
  },
  'music/bridgestone-arena': {
    src: '/media/music/bridgestone-arena.jpg',
    srcSet: '/media/music/bridgestone-arena-640.webp 640w, /media/music/bridgestone-arena-960.webp 960w, /media/music/bridgestone-arena-1600.webp 1600w',
    alt: 'Bridgestone Arena and the Nashville Visitor Center on Broadway.',
    credit: 'Warren LeMay from Chicago, IL, United States',
    licence: 'CC BY-SA 2.0 — https://commons.wikimedia.org/wiki/File%3ANashville_Visitor_Center_and_Bridgestone_Arena%2C_Broadway_and_5th_Avenue%2C_Nashville%2C_TN_%2854384487819%29.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 2399,
    height: 3200,
  },
  'music/ryman-auditorium': {
    src: '/media/music/ryman-auditorium.jpg',
    srcSet: '/media/music/ryman-auditorium-640.webp 640w, /media/music/ryman-auditorium-960.webp 960w, /media/music/ryman-auditorium-1600.webp 1600w, /media/music/ryman-auditorium-2400.webp 2400w',
    alt: 'Exterior of the Ryman Auditorium on Fifth Avenue in Nashville.',
    credit: 'Warren LeMay from Chicago, IL, United States',
    licence: 'CC BY-SA 2.0 — https://commons.wikimedia.org/wiki/File%3ARyman_Auditorium%2C_5th_Avenue%2C_Nashville%2C_TN_%2854384525798%29.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 2400,
    height: 3200,
  },
  'music/station-inn': {
    src: '/media/music/station-inn.jpg',
    srcSet: '/media/music/station-inn-640.webp 640w, /media/music/station-inn-960.webp 960w, /media/music/station-inn-1600.webp 1600w, /media/music/station-inn-2400.webp 2400w',
    alt: 'Exterior of Station Inn in Nashville.',
    credit: 'Nick Shields',
    licence: 'CC BY 2.0 — https://commons.wikimedia.org/wiki/File%3AStation_Inn_Nashville_%288729882676%29.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2400,
  },
  'neighborhood/12-south': {
    src: '/media/neighborhoods/12-south.jpg',
    srcSet: '/media/neighborhoods/12-south-640.webp 640w, /media/neighborhoods/12-south-960.webp 960w, /media/neighborhoods/12-south-1600.webp 1600w, /media/neighborhoods/12-south-2400.webp 2400w',
    alt: 'The I Believe in Nashville mural in 12 South.',
    credit: 'https://www.flickr.com/photos/jamesonfink/',
    licence: 'CC BY 2.0 — https://commons.wikimedia.org/wiki/File%3AI_Believe_in_Nashville_Mural_Jameson_Fink.jpg (Landscape crop keeping the complete mural visible.; Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2133,
  },
  'neighborhood/downtown-broadway': {
    src: '/media/neighborhoods/downtown-broadway.jpg',
    srcSet: '/media/neighborhoods/downtown-broadway-640.webp 640w, /media/neighborhoods/downtown-broadway-960.webp 960w, /media/neighborhoods/downtown-broadway-1600.webp 1600w, /media/neighborhoods/downtown-broadway-2400.webp 2400w',
    alt: 'Lower Broadway at Fourth Avenue in downtown Nashville.',
    credit: 'Warren LeMay from Chicago, IL, United States',
    licence: 'CC BY-SA 2.0 — https://commons.wikimedia.org/wiki/File%3ABroadway_and_4th_Avenue%2C_Nashville%2C_TN_%2854384489114%29.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2400,
  },
  'neighborhood/east-nashville': {
    src: '/media/neighborhoods/east-nashville.jpg',
    srcSet: '/media/neighborhoods/east-nashville-640.webp 640w, /media/neighborhoods/east-nashville-960.webp 960w, /media/neighborhoods/east-nashville-1600.webp 1600w',
    alt: 'Streetscape in East Nashville.',
    credit: 'Andrew Jameson',
    licence: 'CC BY-SA 3.0 — https://commons.wikimedia.org/wiki/File%3AEastNashvilleHD.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 1139,
  },
  'neighborhood/germantown': {
    src: '/media/neighborhoods/germantown.jpg',
    srcSet: '/media/neighborhoods/germantown-640.webp 640w, /media/neighborhoods/germantown-960.webp 960w, /media/neighborhoods/germantown-1600.webp 1600w',
    alt: 'Streetscape in Germantown, Nashville.',
    credit: 'Andrew Jameson',
    licence: 'CC BY-SA 3.0 — https://commons.wikimedia.org/wiki/File%3AGermantownHDNashville.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 1177,
  },
  'neighborhood/green-hills': {
    src: '/media/neighborhoods/green-hills.jpg',
    srcSet: '/media/neighborhoods/green-hills-640.webp 640w, /media/neighborhoods/green-hills-960.webp 960w, /media/neighborhoods/green-hills-1600.webp 1600w, /media/neighborhoods/green-hills-2400.webp 2400w',
    alt: 'The Mall at Green Hills in Nashville.',
    credit: 'TenPoundHammer',
    licence: 'CC BY-SA 4.0 — https://commons.wikimedia.org/wiki/File%3AGreen_hills_1.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 2486,
    height: 3200,
  },
  'neighborhood/hillsboro-village': {
    src: '/media/neighborhoods/hillsboro-village.jpg',
    srcSet: '/media/neighborhoods/hillsboro-village-640.webp 640w, /media/neighborhoods/hillsboro-village-960.webp 960w, /media/neighborhoods/hillsboro-village-1600.webp 1600w, /media/neighborhoods/hillsboro-village-2400.webp 2400w',
    alt: 'The Belcourt Theatre in Hillsboro Village.',
    credit: 'CEWall',
    licence: 'CC BY-SA 4.0 — https://commons.wikimedia.org/wiki/File%3ADSCF9014-crop1.jpg',
    width: 2812,
    height: 1405,
  },
  'neighborhood/midtown': {
    src: '/media/neighborhoods/midtown.jpg',
    srcSet: '/media/neighborhoods/midtown-640.webp 640w, /media/neighborhoods/midtown-960.webp 960w, /media/neighborhoods/midtown-1600.webp 1600w, /media/neighborhoods/midtown-2400.webp 2400w',
    alt: 'Midtown Nashville street view.',
    credit: 'md. childress',
    licence: 'CC BY 3.0 — https://commons.wikimedia.org/wiki/File%3AMidtown%2C_Nashville%2C_TN%2C_USA_-_panoramio.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 1913,
  },
  'neighborhood/sylvan-park': {
    src: '/media/neighborhoods/sylvan-park.jpg',
    srcSet: '/media/neighborhoods/sylvan-park-640.webp 640w, /media/neighborhoods/sylvan-park-960.webp 960w, /media/neighborhoods/sylvan-park-1600.webp 1600w, /media/neighborhoods/sylvan-park-2400.webp 2400w',
    alt: 'St. Andrew\'s Anglican Church in the Sylvan Park area of Nashville.',
    credit: 'Dclemens1971',
    licence: 'CC BY-SA 4.0 — https://commons.wikimedia.org/wiki/File%3ASt._Andrew%E2%80%99s_Anglican_Church%2C_Nashville_01.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2400,
  },
  'neighborhood/the-gulch': {
    src: '/media/neighborhoods/the-gulch.jpg',
    srcSet: '/media/neighborhoods/the-gulch-640.webp 640w, /media/neighborhoods/the-gulch-960.webp 960w, /media/neighborhoods/the-gulch-1600.webp 1600w, /media/neighborhoods/the-gulch-2400.webp 2400w',
    alt: 'Nashville skyline viewed from the Gulch.',
    credit: 'Marlamorrismusic',
    licence: 'CC BY-SA 4.0 — https://commons.wikimedia.org/wiki/File%3ACity_of_Nashville_skyline_from_Gulch_-_Oct_2019.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 1648,
  },
  'stay/value-stays-midtown': {
    src: '/media/stay/value-stays-midtown.jpg',
    srcSet: '/media/stay/value-stays-midtown-640.webp 640w, /media/stay/value-stays-midtown-960.webp 960w, /media/stay/value-stays-midtown-1600.webp 1600w, /media/stay/value-stays-midtown-2400.webp 2400w',
    alt: 'Midtown Nashville street view.',
    credit: 'md. childress',
    licence: 'CC BY 3.0 — https://commons.wikimedia.org/wiki/File%3AMidtown%2C_Nashville%2C_TN%2C_USA_-_panoramio.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 1913,
  },
  'stay/walkable-to-broadway': {
    src: '/media/stay/walkable-to-broadway.jpg',
    srcSet: '/media/stay/walkable-to-broadway-640.webp 640w, /media/stay/walkable-to-broadway-960.webp 960w, /media/stay/walkable-to-broadway-1600.webp 1600w, /media/stay/walkable-to-broadway-2400.webp 2400w',
    alt: 'Lower Broadway at Fourth Avenue in downtown Nashville.',
    credit: 'Warren LeMay from Chicago, IL, United States',
    licence: 'CC BY-SA 2.0 — https://commons.wikimedia.org/wiki/File%3ABroadway_and_4th_Avenue%2C_Nashville%2C_TN_%2854384489114%29.jpg (Resized master longest edge to 3200px (no upscale).)',
    width: 3200,
    height: 2400,
  },
} as const satisfies Record<string, MediaAsset>;

export const RESTORED_MEDIA_KEYS = Object.keys(restoredMedia) as Array<keyof typeof restoredMedia>;

/** Adobe Stock IDs pending Eric purchase — never render until licensed original is on disk. */
export const adobePurchaseMedia = {
  'guide/where-to-stay': {
    src: '/media/guides/where-to-stay-nashville.jpg',
    alt: 'Downtown Nashville skyline along the Cumberland at blue hour.',
    credit: 'Adobe Stock #1103549851 (purchase required)',
    licence: 'Adobe Stock #1103549851 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'guide/best-things-to-do': {
    src: '/media/guides/best-things-to-do-nashville.jpg',
    alt: 'Nashville skyline and John Seigenthaler Pedestrian Bridge at dusk.',
    credit: 'Adobe Stock #238367153 (purchase required)',
    licence: 'Adobe Stock #238367153 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'guide/weekend-itinerary': {
    src: '/media/guides/nashville-weekend-itinerary.jpg',
    alt: 'Nashville Tennessee skyline.',
    credit: 'Adobe Stock #179552781 (purchase required)',
    licence: 'Adobe Stock #179552781 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'guide/bachelorette': {
    src: '/media/guides/nashville-bachelorette-guide.jpg',
    alt: 'Friends celebrating together at a rooftop bachelorette party.',
    credit: 'Adobe Stock #205821520 (purchase required)',
    licence: 'Adobe Stock #205821520 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'guide/with-kids': {
    src: '/media/guides/nashville-with-kids.jpg',
    alt: 'A family spending time together outdoors in a city park.',
    credit: 'Adobe Stock #254050330 (purchase required)',
    licence: 'Adobe Stock #254050330 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'attractions/shelby-bottoms-greenway': {
    src: '/media/attractions/shelby-bottoms-greenway.jpg',
    alt: 'Pathways along Shelby Bottoms Greenway in Nashville.',
    credit: 'Adobe Stock #259662137 (purchase required)',
    licence: 'Adobe Stock #259662137 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'stay/boutique-hotels-downtown': {
    src: '/media/stay/boutique-hotels-downtown.jpg',
    alt: 'Interior of a luxury hotel lobby reception area.',
    credit: 'Adobe Stock #117735176 (purchase required)',
    licence: 'Adobe Stock #117735176 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'stay/group-rentals': {
    src: '/media/stay/group-rentals.jpg',
    alt: 'Group of friends enjoying a vacation together.',
    credit: 'Adobe Stock #171188671 (purchase required)',
    licence: 'Adobe Stock #171188671 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'stay/luxury-resorts-opryland': {
    src: '/media/stay/luxury-resorts-opryland.jpg',
    alt: 'A large resort hotel atrium.',
    credit: 'Adobe Stock #116459645 (purchase required)',
    licence: 'Adobe Stock #116459645 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'stay/hotels-with-pools': {
    src: '/media/stay/hotels-with-pools.jpg',
    alt: 'Relaxing in a rooftop pool with a city skyline view at dusk.',
    credit: 'Adobe Stock #1642501680 (purchase required)',
    licence: 'Adobe Stock #1642501680 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'hero/nashroam-skyline': {
    src: '/media/hero/nashroam-skyline-hero.jpg',
    alt: 'Nashville, Tennessee skyline over the Cumberland River.',
    credit: 'Adobe Stock #823396314 (purchase required)',
    licence: 'Adobe Stock #823396314 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'hub/hotels-index': {
    src: '/media/hubs/hotels-index.jpg',
    alt: 'Downtown Nashville skyline.',
    credit: 'Adobe Stock #118131119 (purchase required)',
    licence: 'Adobe Stock #118131119 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'hub/where-to-stay': {
    src: '/media/hubs/where-to-stay.jpg',
    alt: 'Downtown Nashville skyline along the Cumberland at blue hour.',
    credit: 'Adobe Stock #1103549851 (purchase required)',
    licence: 'Adobe Stock #1103549851 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'hub/tours-lead': {
    src: '/media/hubs/tours-lead.jpg',
    alt: 'Nashville pedestrian bridge and skyline at sunset.',
    credit: 'Adobe Stock #90286481 (purchase required)',
    licence: 'Adobe Stock #90286481 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'hub/weekend-lead': {
    src: '/media/hubs/weekend-lead.jpg',
    alt: 'Nashville downtown skyline at twilight.',
    credit: 'Adobe Stock #242230333 (purchase required)',
    licence: 'Adobe Stock #242230333 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'hub/events-lead': {
    src: '/media/hubs/events-lead.jpg',
    alt: 'Nashville skyline at blue hour.',
    credit: 'Adobe Stock #309003897 (purchase required)',
    licence: 'Adobe Stock #309003897 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'hub/events-this-weekend': {
    src: '/media/hubs/events-this-weekend.jpg',
    alt: 'Nashville skyline at evening.',
    credit: 'Adobe Stock #73314740 (purchase required)',
    licence: 'Adobe Stock #73314740 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
  'hub/plan-lead': {
    src: '/media/hubs/plan-lead.jpg',
    alt: 'Downtown Nashville skyline and Cumberland River.',
    credit: 'Adobe Stock #268082470 (purchase required)',
    licence: 'Adobe Stock #268082470 — purchase-required; do not use preview; reject Editorial Use Only',
    width: 1600,
    height: 900,
  },
} as const satisfies Record<string, MediaAsset>;

