-- Nashroam FSQ OS Places export
--
-- Run this AFTER pasting the DuckDB/Iceberg connection snippet generated by
-- the Foursquare Places Portal. The Portal currently exposes datasets named
-- `places`, `categories`, and `deltas` in its Iceberg catalog.
--
-- The bounding box below is an operational Nashville capture window, not a
-- legal city/county boundary. It intentionally includes the urban tourism core
-- plus nearby destination areas. Tighten/expand it as the corpus evolves.

-- 1) Export the full FSQ category taxonomy (small; ~1K categories).
COPY (
  SELECT *
  FROM categories
) TO 'fsq-categories.jsonl' (FORMAT JSON, ARRAY false);

-- 2) Export recent/open tourism-relevant Nashville POIs.
COPY (
  SELECT
    fsq_place_id,
    name,
    latitude,
    longitude,
    address,
    locality,
    region,
    postcode,
    country,
    date_created,
    date_refreshed,
    date_closed,
    tel,
    website,
    email,
    facebook_id,
    instagram,
    twitter,
    fsq_category_ids,
    fsq_category_labels,
    placemaker_url,
    unresolved_flags
  FROM places
  WHERE country = 'US'
    AND region = 'TN'
    AND latitude BETWEEN 35.95 AND 36.35
    AND longitude BETWEEN -87.05 AND -86.50
    AND date_closed IS NULL
    AND date_refreshed >= current_date - INTERVAL 365 DAY
    AND NOT list_has_any(
      coalesce(unresolved_flags, []),
      ['closed','duplicate','delete','privatevenue','inappropriate','doesnt_exist']
    )
    AND regexp_matches(
      lower(array_to_string(fsq_category_labels, ' | ')),
      '(restaurant|food|diner|steakhouse|pizzeria|sandwich|seafood|sushi|taco|bakery|bar|pub|cocktail|brewery|wine|night ?club|coffee|cafe|tea room|museum|historic|monument|landmark|art gallery|performing arts|theater|theatre|music venue|concert|zoo|attraction|park|garden|trail|outdoor|recreation|nature preserve|store|shop|boutique|shopping|market|hotel|motel|resort|bed and breakfast)'
    )
) TO 'fsq-nashville-places.jsonl' (FORMAT JSON, ARRAY false);

-- Optional inspection before import:
-- SELECT count(*) FROM read_json_auto('fsq-nashville-places.jsonl');
-- SELECT fsq_category_labels, count(*)
-- FROM read_json_auto('fsq-nashville-places.jsonl')
-- GROUP BY 1 ORDER BY 2 DESC LIMIT 50;
